"""Terminal (curses) renderer for Thronglets.

No GUI/X11/SDL needed - handy on Termux or over plain SSH, where pygame is
painful to install. Only the Python standard library plus numpy are needed.

You pick a language, automatic or manual mode, and whether to seed the AI
language once, at startup - not something you toggle mid-run.

Controls: space=pause  f=drop food (auto mode only)  r=reset  +/-=speed  q=quit
  p=toggle food/predator (manual placement)
  [ / ]=remove/add a predator right now (also sets the count used on reset)
  arrow keys=move cursor, enter=place (manual mode)
  h=in-game notice/help screen
"""

import argparse
import curses
import os
import threading
import time

from i18n import STATE_LABELS, TRAIT_LABELS
from simulation import (DANGER, DISTRESS, FOOD, HEIGHT, IDLE, MATE, MAX_POPULATION, N_TOKENS, N_TRAITS, World, WIDTH,
                         compare_seeds, load_seed_genome, load_world, save_world)

DEFAULT_INIT_POP = 100
DEFAULT_LANGUAGE_FILE = "language_model.json"
DEFAULT_SAVE_FILE = "thronglets_save.json"

TOKEN_COLOR_PAIR = {1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
HUD_H = 10
CURSOR_STEP = 4.0
ENTER_KEYS = (10, 13, curses.KEY_ENTER)

TEXT = {
    "en": {
        "choose_mode_prompt": "Choose the starting mode:",
        "choose_mode_auto": "  A = automatic - food and predators spawn on their own (default)",
        "choose_mode_manual": "  M = manual - you place everything yourself, nothing spawns alone",
        "choose_mode_hint": "Press A or M, or ENTER for the default (automatic).",

        "choose_pop_prompt": "How many creatures to start with? (1-{max}, enter = {default})",

        "choose_traits_prompt": "Adaptive evolution: speed, vision, hearing, metabolism?",
        "choose_traits_explain1": "  Each creature gets its own physical stats, inherited and mutated -",
        "choose_traits_explain2": "  but faster/keener senses cost more energy, so it's a real trade-off.",
        "choose_traits_yes": "  Y = yes - physical traits evolve too, not just signaling",
        "choose_traits_no": "  N = no - everyone has the same fixed stats (default)",
        "choose_traits_hint": "Press Y or N, or ENTER for the default (no).",

        "choose_ai_prompt": "Activate the pre-trained AI language?",
        "choose_ai_subtitle": "  (reads '{file}', generated by train_language.py)",
        "choose_ai_yes": "  Y = yes - creatures already speak an unambiguous language (default)",
        "choose_ai_no": "  N = no - the language has to emerge on its own while you play",
        "choose_ai_hint": "Press Y or N, or ENTER for the default (yes).",
        "ai_missing_file": "'{file}' not found - starting without AI.",
        "flash_hint": "-- press any key to continue --",

        "choose_resume_prompt": "A saved game was found. Resume it?",
        "choose_resume_subtitle": "  (reads '{file}' - the population, food, and predators as you left them)",
        "choose_resume_yes": "  Y = yes - pick up exactly where you left off",
        "choose_resume_no": "  N = no - start a fresh game instead",
        "choose_resume_hint": "Press Y or N to continue.",
        "resume_load_failed": "'{file}' could not be read - starting a fresh game instead.",
        "save_confirmed": "Game saved to '{file}'.",

        "hud_paused": "PAUSED",
        "hud_trained_tag": "  [trained vocabulary]",
        "hud_traits_tag": "  [adaptive traits]",
        "hud_header": "tick {tick}  pop {pop}  births {births}  deaths {deaths}  {status}{tag}",
        "hud_manual": "mode: manual   arrows+enter place: {placing} (tab)",
        "hud_auto": "mode: automatic   predators: {count} ([ ] act immediately)",
        "placing_food": "food",
        "placing_predator": "predator",
        "hud_legend": "colored o = signaling   white o = silent   . = food   X = predator",
        "hud_controls1": "space=pause  n=food  p=predator  r=reset  +/-=speed  q=quit",
        "hud_controls2": "[ ]=predator count  s=save  arrows+enter=place (tab=switch)  g=graph  t=family  c=compare  d=translator  F=faq  h=help",
        "graph_title": "Vocabulary over time - dominant share per state",
        "graph_traits_title": "Physical traits over time - population average (share of range)",
        "graph_dismiss": "-- press any key to go back --",
        "extinct": "Extinct. Press r to reset.",

        "translator_title": "Translator - what each color currently means",
        "translator_unused": "unused / ambiguous",
        "translator_homonym": "  ! homonym - shared with another state",
        "translator_dismiss": "-- press any key to go back --",

        "family_title": "Family tree",
        "family_gen": "generation {gen}",
        "family_alive": "alive - token {token}, age {age}",
        "family_dead": "dead since tick {death}",
        "family_born": "born at tick {tick}",
        "family_parents": "Parents:",
        "family_founder": "none - founding generation",
        "family_children": "Children ({n}):",
        "family_no_children": "none yet",
        "family_descendants": "Total descendants: {total} ({alive} still alive)",
        "family_hint": "UP=parent  DOWN=child  LEFT/RIGHT=siblings  -- t or ESC to go back --",
        "family_none": "No creature to show yet.",
        "family_dismiss": "-- press any key to go back --",

        "compare_mode_prompt": "Compare seeds: what should be reproducible?",
        "compare_mode_language": "  L = language - does the same word win across independent runs?",
        "compare_mode_traits": "  T = physical traits - do speed/vision/hearing/metabolism converge the same way?",
        "compare_mode_traits_unavailable": "  (traits unavailable - adaptive evolution is off for this world)",
        "compare_mode_hint": "Press L or T, or ESC to cancel.",
        "compare_depth_prompt": "How thorough?",
        "compare_depth_quick": "  R = quick - 4 seeds x 8,000 ticks (default)",
        "compare_depth_thorough": "  A = thorough - 8 seeds x 40,000 ticks",
        "compare_depth_expert": "  E = expert - 16 seeds x 60,000 ticks, one at a time - can take a while",
        "compare_depth_hint": "Press R, A, or E, or ENTER for the default (quick). ESC cancels.",
        "compare_progress": "seed {seed}/{n_seeds}   tick {tick}/{ticks}   ESC cancels",
        "compare_result_title": "Comparison done ({n_seeds} seeds x {ticks} ticks)",
        "compare_traits_header": "trait          mean    std dev   min      max",
        "compare_lang_header": "state          seeds' dominant color",
        "compare_collision_summary": "Collisions: {clean}/{n_seeds} seeds had none",
        "compare_dismiss": "-- press any key to go back --",
        "compare_cancelled": "Cancelled - {n} seed(s) completed before stopping.",

        "help_more": "-- space for more --",
        "help_dismiss": "-- press any key to resume --",
    },
    "fr": {
        "choose_mode_prompt": "Choisis le mode de depart :",
        "choose_mode_auto": "  A = automatique - nourriture et predateurs apparaissent seuls (defaut)",
        "choose_mode_manual": "  M = manuel - tu places tout toi-meme, rien ne spawn seul",
        "choose_mode_hint": "Appuie sur A ou M, ou ENTREE pour le defaut (auto).",

        "choose_pop_prompt": "Combien de creatures au depart ? (1-{max}, entree = {default})",

        "choose_traits_prompt": "Evolution adaptative : vitesse, vision, ouie, metabolisme ?",
        "choose_traits_explain1": "  Chaque creature a ses propres stats physiques, heritees et mutees -",
        "choose_traits_explain2": "  mais etre rapide/perceptif coute plus d'energie, un vrai compromis.",
        "choose_traits_yes": "  O = oui - les traits physiques evoluent aussi, pas juste le langage",
        "choose_traits_no": "  N = non - tout le monde a les memes stats fixes (defaut)",
        "choose_traits_hint": "Appuie sur O ou N, ou ENTREE pour le defaut (non).",

        "choose_ai_prompt": "Activer le langage pre-entraine par IA ?",
        "choose_ai_subtitle": "  (relit '{file}', genere par train_language.py)",
        "choose_ai_yes": "  O = oui - les creatures parlent deja un langage sans confusion (defaut)",
        "choose_ai_no": "  N = non - le langage doit emerger tout seul en jouant",
        "choose_ai_hint": "Appuie sur O ou N, ou ENTREE pour le defaut (oui).",
        "ai_missing_file": "'{file}' introuvable - lancement sans IA.",
        "flash_hint": "-- une touche pour continuer --",

        "choose_resume_prompt": "Une partie sauvegardee existe. La reprendre ?",
        "choose_resume_subtitle": "  (relit '{file}' - la population, la nourriture et les predateurs tels que laisses)",
        "choose_resume_yes": "  O = oui - reprendre exactement ou tu t'es arrete",
        "choose_resume_no": "  N = non - commencer une nouvelle partie",
        "choose_resume_hint": "Appuie sur O ou N pour continuer.",
        "resume_load_failed": "'{file}' illisible - nouvelle partie a la place.",
        "save_confirmed": "Partie sauvegardee dans '{file}'.",

        "hud_paused": "PAUSE",
        "hud_trained_tag": "  [vocabulaire entraine]",
        "hud_traits_tag": "  [traits evolutifs]",
        "hud_header": "tick {tick}  pop {pop}  naissances {births}  morts {deaths}  {status}{tag}",
        "hud_manual": "mode: manuel   fleches+entree pose : {placing} (tab)",
        "hud_auto": "mode: auto   predateurs: {count} ([ ] agit tout de suite)",
        "placing_food": "nourriture",
        "placing_predator": "predateur",
        "hud_legend": "o colore = signale   o blanc = silencieuse   . = nourriture   X = predateur",
        "hud_controls1": "space=pause  n=nourriture  p=predateur  r=reset  +/-=vitesse  q=quitter",
        "hud_controls2": "[ ]=nb predateurs  s=sauver  fleches+entree=placer (tab=changer)  g=graphique  t=famille  c=comparer  d=traducteur  F=faq  h=aide",
        "graph_title": "Vocabulaire dans le temps - part dominante par etat",
        "graph_traits_title": "Traits physiques dans le temps - moyenne population (part de la plage)",
        "graph_dismiss": "-- une touche pour revenir --",
        "extinct": "Extinction. Appuie sur r pour recommencer.",

        "translator_title": "Traducteur - ce que signifie chaque couleur en ce moment",
        "translator_unused": "inutilisee / ambigue",
        "translator_homonym": "  ! homonymie - partagee avec un autre etat",
        "translator_dismiss": "-- une touche pour revenir --",

        "family_title": "Arbre genealogique",
        "family_gen": "generation {gen}",
        "family_alive": "vivant - token {token}, age {age}",
        "family_dead": "mort depuis le tick {death}",
        "family_born": "ne au tick {tick}",
        "family_parents": "Parents :",
        "family_founder": "aucun - generation fondatrice",
        "family_children": "Enfants ({n}) :",
        "family_no_children": "aucun pour le moment",
        "family_descendants": "Descendants au total : {total} ({alive} encore en vie)",
        "family_hint": "HAUT=parent  BAS=enfant  GAUCHE/DROITE=freres et soeurs  -- t ou ESC pour revenir --",
        "family_none": "Aucune creature a montrer pour le moment.",
        "family_dismiss": "-- une touche pour revenir --",

        "compare_mode_prompt": "Comparer des seeds : qu'est-ce qui doit etre reproductible ?",
        "compare_mode_language": "  L = langage - le meme mot gagne-t-il sur des parties independantes ?",
        "compare_mode_traits": "  T = traits physiques - vitesse/vision/ouie/metabolisme convergent-ils pareil ?",
        "compare_mode_traits_unavailable": "  (traits indisponibles - evolution adaptative desactivee pour ce monde)",
        "compare_mode_hint": "Appuie sur L ou T, ou ESC pour annuler.",
        "compare_depth_prompt": "Quelle profondeur ?",
        "compare_depth_quick": "  R = rapide - 4 seeds x 8 000 ticks (defaut)",
        "compare_depth_thorough": "  A = approfondi - 8 seeds x 40 000 ticks",
        "compare_depth_expert": "  E = expert - 16 seeds x 60 000 ticks, une par une - peut prendre du temps",
        "compare_depth_hint": "Appuie sur R, A ou E, ou ENTREE pour le defaut (rapide). ESC annule.",
        "compare_progress": "seed {seed}/{n_seeds}   tick {tick}/{ticks}   ESC annule",
        "compare_result_title": "Comparaison terminee ({n_seeds} seeds x {ticks} ticks)",
        "compare_traits_header": "trait          moyenne ecart-type  min      max",
        "compare_lang_header": "etat           couleur dominante par seed",
        "compare_collision_summary": "Collisions : {clean}/{n_seeds} seeds sans collision",
        "compare_dismiss": "-- une touche pour revenir --",
        "compare_cancelled": "Annule - {n} seed(s) terminee(s) avant l'arret.",

        "help_more": "-- espace pour la suite --",
        "help_dismiss": "-- une touche pour reprendre --",
    },
}

HELP_LINES = {
    "en": [
        ("Thronglets - notice", curses.A_BOLD),
        ("", 0),
        ("Each creature is born with a genome deciding which color it shows", 0),
        ("for its current state, and how it reacts to colors it hears from", 0),
        ("others. Nobody programs what a color means - a shared language can", 0),
        ("emerge through natural selection, or it might not.", 0),
        ("", 0),
        ("The 5 states, in priority order:", curses.A_BOLD),
        ("  1. alarm-call    a predator was spotted -> flee immediately", 0),
        ("  2. food-call     food is visible nearby", 0),
        ("  3. distress-call energy critically low, no food in sight", 0),
        ("  4. mate-call     ready to mate, and a ready partner is nearby", 0),
        ("  5. idle          nothing special (by far the most common state)", 0),
        ("", 0),
        ("Living, mating, dying:", curses.A_BOLD),
        ("  Energy drains constantly; eating restores it. Emitting a color", 0),
        ("  (other than silence) costs a bit of extra energy. Enough energy", 0),
        ("  and age, plus a matching partner nearby: a child is born. A", 0),
        ("  predator that catches a creature kills it outright.", 0),
        ("", 0),
        ("Reading the vocabulary rows at the top:", curses.A_BOLD),
        ("  For each state, the share of the population using each color.", 0),
        ("  It starts near chance (~17%) and climbs if a token wins out.", 0),
        ("  A '..' swatch means silence, not a missing color.", 0),
        ("", 0),
        ("Worth knowing:", curses.A_BOLD),
        ("  Two states can end up sharing the same color purely by chance", 0),
        ("  (e.g. idle and alarm-call) - nothing prevents it or guarantees", 0),
        ("  it resolves. Signaling costs energy, so silence is a real", 0),
        ("  strategy, not a default.", 0),
    ],
    "fr": [
        ("Thronglets — notice", curses.A_BOLD),
        ("", 0),
        ("Chaque creature nait avec un genome qui decide quelle couleur", 0),
        ("elle affiche selon son etat, et comment elle reagit aux couleurs", 0),
        ("des autres. Personne ne programme le sens des couleurs : un", 0),
        ("langage commun peut emerger par selection naturelle, ou pas.", 0),
        ("", 0),
        ("Les 5 etats, par ordre de priorite :", curses.A_BOLD),
        ("  1. alerte     un predateur repere -> fuite immediate", 0),
        ("  2. nourriture de la nourriture est visible tout pres", 0),
        ("  3. detresse   energie tres basse, aucune nourriture en vue", 0),
        ("  4. partenaire prete a se reproduire + partenaire prete proche", 0),
        ("  5. inactif    rien de special (etat le plus frequent, de loin)", 0),
        ("", 0),
        ("Vivre, se reproduire, mourir :", curses.A_BOLD),
        ("  L'energie baisse en permanence, manger la restaure. Emettre", 0),
        ("  une couleur (hors silence) coute un peu d'energie en plus.", 0),
        ("  Assez d'energie et d'age, un partenaire pareil a proximite :", 0),
        ("  un enfant nait. Un predateur qui attrape une creature la tue.", 0),
        ("", 0),
        ("Lire le vocabulaire affiche en haut :", curses.A_BOLD),
        ("  Pour chaque etat, la part de la population qui utilise chaque", 0),
        ("  couleur. Ca part du hasard (~17%) et grimpe si un mot fait", 0),
        ("  consensus. '..' = silence, pas une couleur en moins.", 0),
        ("", 0),
        ("A savoir :", curses.A_BOLD),
        ("  Deux etats peuvent finir sur la meme couleur par hasard (ex:", 0),
        ("  inactif et alerte) - rien ne l'empeche ni ne garantit que ca", 0),
        ("  se resolve. Parler coute de l'energie : le silence est une", 0),
        ("  vraie strategie, pas un defaut.", 0),
    ],
}


def show_help(stdscr, lang):
    """Paginate so this fits any terminal height, not just tall ones."""
    stdscr.nodelay(False)
    rows, _ = stdscr.getmaxyx()
    lines = HELP_LINES[lang]
    page_size = max(1, rows - 2)
    for start in range(0, len(lines), page_size):
        page = lines[start:start + page_size]
        stdscr.erase()
        for i, (line, attr) in enumerate(page):
            _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
        more = start + page_size < len(lines)
        footer = TEXT[lang]["help_more"] if more else TEXT[lang]["help_dismiss"]
        _safe_addstr(stdscr, min(rows - 1, len(page) + 1), 0, footer, curses.color_pair(7) | curses.A_DIM)
        stdscr.refresh()
        stdscr.getch()
    stdscr.nodelay(True)


FAQ_LINES = {
    "en": [
        ("Thronglets - FAQ", curses.A_BOLD),
        ("", 0),
        ("Q: Why do creatures sometimes stay clustered even with food right", curses.A_BOLD),
        ("   next to them?", curses.A_BOLD),
        ("A: Following a neighbor's signal and heading for food are two", 0),
        ("   forces that can partly cancel out - an accepted trade-off,", 0),
        ("   not a bug.", 0),
        ("", 0),
        ("Q: Does distress make creatures help each other?", curses.A_BOLD),
        ("A: No - there's no cooperation mechanic. Distress is treated like", 0),
        ("   any other signal, and creatures mostly learn to avoid it.", 0),
        ("", 0),
        ("Q: Why does the adaptive metabolism trait always drop to near its", curses.A_BOLD),
        ("   minimum?", curses.A_BOLD),
        ("A: Unlike speed/vision/hearing, a lower metabolism has zero", 0),
        ("   downside here - it's not a real trade-off, so selection", 0),
        ("   always pushes it down.", 0),
        ("", 0),
        ("Q: How can two creatures from very different generations be", curses.A_BOLD),
        ("   siblings?", curses.A_BOLD),
        ("A: Generation = max(both parents' generations)+1, and mate choice", 0),
        ("   only cares about proximity, not generation - a long-lived", 0),
        ("   parent can breed with a much 'deeper' partner late in life.", 0),
        ("", 0),
        ("Q: Can a creature really mate with its own descendant?", curses.A_BOLD),
        ("A: Yes - same reason: mate choice is purely proximity-based,", 0),
        ("   with no notion of family.", 0),
        ("", 0),
        ("Q: Even a trained vocabulary can drift or 'flip back' - why?", curses.A_BOLD),
        ("A: No creature learns anything during its life; genomes are", 0),
        ("   fixed at birth. Only mutation and selection across", 0),
        ("   generations change anything, and mutation never stops -", 0),
        ("   nothing is ever permanently locked in.", 0),
        ("", 0),
        ("Q: Two states share the same color (homonymy) - is that a bug?", curses.A_BOLD),
        ("A: No - nothing in the model prevents it. Genomes mutate per", 0),
        ("   state independently, so two states can land on the same", 0),
        ("   token by pure chance. Check the Translator screen (d) to", 0),
        ("   see it clearly.", 0),
        ("", 0),
        ("Q: A single playthrough shows a surprising result - can I trust", curses.A_BOLD),
        ("   it?", curses.A_BOLD),
        ("A: Not on its own. Use the Compare screen (c) to run several", 0),
        ("   independent seeds and see whether the result actually", 0),
        ("   repeats, or was just one run's drift.", 0),
        ("", 0),
        ("Q: What's the real difference between the trained AI language", curses.A_BOLD),
        ("   and the evolved one?", curses.A_BOLD),
        ("A: The AI (train_language.py) uses gradient descent to directly", 0),
        ("   minimize communication error, every step. The evolved", 0),
        ("   language only rewards survival and reproduction - comm-", 0),
        ("   unicating well is never optimized directly, just indirectly", 0),
        ("   useful.", 0),
    ],
    "fr": [
        ("Thronglets — FAQ", curses.A_BOLD),
        ("", 0),
        ("Q : Pourquoi les creatures restent parfois en groupe meme avec", curses.A_BOLD),
        ("    de la nourriture juste a cote ?", curses.A_BOLD),
        ("R : Suivre le signal d'un voisin et se diriger vers la", 0),
        ("    nourriture sont deux forces qui peuvent s'annuler en", 0),
        ("    partie - un compromis assume, pas un bug.", 0),
        ("", 0),
        ("Q : Est-ce que la detresse pousse les creatures a s'entraider ?", curses.A_BOLD),
        ("R : Non - il n'y a aucun mecanisme de cooperation. La detresse", 0),
        ("    est traitee comme n'importe quel autre signal, et les", 0),
        ("    creatures apprennent surtout a l'eviter.", 0),
        ("", 0),
        ("Q : Pourquoi le metabolisme adaptatif tombe toujours pres de", curses.A_BOLD),
        ("    son minimum ?", curses.A_BOLD),
        ("R : Contrairement a la vitesse/vision/ouie, un metabolisme bas", 0),
        ("    n'a aucun inconvenient ici - ce n'est pas un vrai", 0),
        ("    compromis, donc la selection le pousse toujours vers le", 0),
        ("    bas.", 0),
        ("", 0),
        ("Q : Comment deux creatures de generations tres differentes", curses.A_BOLD),
        ("    peuvent-elles etre frere et soeur ?", curses.A_BOLD),
        ("R : Generation = max(generation des deux parents)+1, et le", 0),
        ("    choix du partenaire ne tient compte que de la proximite,", 0),
        ("    pas de la generation - un parent qui vit longtemps peut se", 0),
        ("    reproduire avec un partenaire bien plus 'profond' tard", 0),
        ("    dans sa vie.", 0),
        ("", 0),
        ("Q : Une creature peut-elle vraiment s'accoupler avec son propre", curses.A_BOLD),
        ("    descendant ?", curses.A_BOLD),
        ("R : Oui - meme raison : le choix du partenaire est purement", 0),
        ("    base sur la proximite, sans aucune notion de famille.", 0),
        ("", 0),
        ("Q : Meme un vocabulaire entraine peut deriver ou 'revenir en", curses.A_BOLD),
        ("    arriere' - pourquoi ?", curses.A_BOLD),
        ("R : Aucune creature n'apprend quoi que ce soit pendant sa vie ;", 0),
        ("    les genomes sont fixes a la naissance. Seules la mutation", 0),
        ("    et la selection a travers les generations changent quelque", 0),
        ("    chose, et la mutation ne s'arrete jamais - rien n'est", 0),
        ("    jamais definitivement acquis.", 0),
        ("", 0),
        ("Q : Deux etats partagent la meme couleur (homonymie) - c'est", curses.A_BOLD),
        ("    un bug ?", curses.A_BOLD),
        ("R : Non - rien dans le modele ne l'empeche. Les genomes mutent", 0),
        ("    independamment par etat, donc deux etats peuvent tomber", 0),
        ("    sur le meme token par pur hasard. L'ecran Traducteur (d)", 0),
        ("    permet de le reperer clairement.", 0),
        ("", 0),
        ("Q : Une seule partie donne un resultat surprenant - puis-je lui", curses.A_BOLD),
        ("    faire confiance ?", curses.A_BOLD),
        ("R : Pas telle quelle. Utilise l'ecran Comparer (c) pour lancer", 0),
        ("    plusieurs seeds independantes et voir si le resultat se", 0),
        ("    reproduit vraiment, ou si c'etait juste la derive d'une", 0),
        ("    seule partie.", 0),
        ("", 0),
        ("Q : Quelle est la vraie difference entre le langage entraine", curses.A_BOLD),
        ("    par IA et celui qui evolue ?", curses.A_BOLD),
        ("R : L'IA (train_language.py) utilise la descente de gradient", 0),
        ("    pour minimiser directement l'erreur de communication, a", 0),
        ("    chaque etape. Le langage evolue ne recompense que la", 0),
        ("    survie et la reproduction - bien communiquer n'est jamais", 0),
        ("    optimise directement, juste utile indirectement.", 0),
    ],
}


def show_faq(stdscr, lang):
    """Paginated the same way as show_help() - curated questions that came
    up while building/playing this, with honest, specific answers."""
    stdscr.nodelay(False)
    rows, _ = stdscr.getmaxyx()
    lines = FAQ_LINES[lang]
    page_size = max(1, rows - 2)
    for start in range(0, len(lines), page_size):
        page = lines[start:start + page_size]
        stdscr.erase()
        for i, (line, attr) in enumerate(page):
            _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
        more = start + page_size < len(lines)
        footer = TEXT[lang]["help_more"] if more else TEXT[lang]["help_dismiss"]
        _safe_addstr(stdscr, min(rows - 1, len(page) + 1), 0, footer, curses.color_pair(7) | curses.A_DIM)
        stdscr.refresh()
        stdscr.getch()
    stdscr.nodelay(True)


def setup_colors():
    curses.start_color()
    curses.use_default_colors()
    curses.init_pair(1, curses.COLOR_RED, -1)
    curses.init_pair(2, curses.COLOR_BLUE, -1)
    curses.init_pair(3, curses.COLOR_YELLOW, -1)
    curses.init_pair(4, curses.COLOR_MAGENTA, -1)
    curses.init_pair(5, curses.COLOR_CYAN, -1)
    curses.init_pair(6, curses.COLOR_GREEN, -1)   # food
    curses.init_pair(7, curses.COLOR_WHITE, -1)   # hud / body


def _safe_addstr(stdscr, y, x, text, attr):
    rows, cols = stdscr.getmaxyx()
    if 0 <= y < rows and 0 <= x < cols:
        try:
            stdscr.addstr(y, x, text[: cols - x], attr)
        except curses.error:
            pass


SPARK_CHARS = " ▁▂▃▄▅▆▇█"  # blank + 8 block levels


def _sparkline(history, width=24):
    """Renders the *entire* history compressed into `width` characters, not
    just its tail end - so the curve always spans the whole run, the same
    way the pygame/web renderers' line plots naturally do."""
    if not history:
        return SPARK_CHARS[0] * width
    values = list(history)
    if len(values) <= width:
        chars = [SPARK_CHARS[0]] * (width - len(values)) + [
            SPARK_CHARS[1 + min(7, int(v * 8))] for v in values
        ]
    else:
        bucket = len(values) / width
        chars = []
        for i in range(width):
            lo, hi = int(i * bucket), max(int(i * bucket) + 1, int((i + 1) * bucket))
            avg = sum(values[lo:hi]) / (hi - lo)
            chars.append(SPARK_CHARS[1 + min(7, int(avg * 8))])
    return "".join(chars)


def _draw_vocab_row(stdscr, y, label, pairs):
    x = 0
    _safe_addstr(stdscr, y, x, f"{label}:", curses.color_pair(7) | curses.A_BOLD)
    x += len(label) + 2
    for token, frac in pairs:
        if token == 0:
            _safe_addstr(stdscr, y, x, "..", curses.color_pair(7) | curses.A_DIM)
        else:
            _safe_addstr(stdscr, y, x, "##", curses.color_pair(TOKEN_COLOR_PAIR[token]) | curses.A_BOLD)
        seg = f"{frac * 100:3.0f}% "
        _safe_addstr(stdscr, y, x + 2, seg, curses.color_pair(7))
        x += 2 + len(seg)


def show_graph(stdscr, world, lang):
    """A dedicated full-screen view of vocab_history, opened like show_help()
    - the HUD rows stay compact, this is where the curves get room to breathe."""
    t = TEXT[lang]
    labels = STATE_LABELS[lang]
    stdscr.nodelay(False)
    stdscr.erase()
    rows, cols = stdscr.getmaxyx()
    width = max(10, cols - 20)

    _safe_addstr(stdscr, 0, 0, t["graph_title"], curses.color_pair(7) | curses.A_BOLD)

    y = 2
    for state in (DANGER, FOOD, DISTRESS, MATE, IDLE):
        if y + 1 >= rows - 1:
            break
        history = world.vocab_history[state]
        current = f"{history[-1] * 100:3.0f}%" if history else "  -%"
        _safe_addstr(stdscr, y, 0, f"{labels[state]:<14} {current}", curses.color_pair(7) | curses.A_BOLD)
        _safe_addstr(stdscr, y + 1, 0, _sparkline(history, width), curses.color_pair(6))
        y += 3

    if world.adaptive_traits and y + 1 < rows - 1:
        y += 1
        trait_labels = TRAIT_LABELS[lang]
        _safe_addstr(stdscr, y, 0, t["graph_traits_title"], curses.color_pair(7) | curses.A_BOLD)
        y += 2
        for trait in range(N_TRAITS):
            if y + 1 >= rows - 1:
                break
            history = world.trait_history[trait]
            current = f"{history[-1] * 100:3.0f}%" if history else "  -%"
            _safe_addstr(stdscr, y, 0, f"{trait_labels[trait]:<14} {current}", curses.color_pair(7) | curses.A_BOLD)
            _safe_addstr(stdscr, y + 1, 0, _sparkline(history, width), curses.color_pair(5))
            y += 3

    _safe_addstr(stdscr, min(rows - 1, y), 0, t["graph_dismiss"], curses.color_pair(7) | curses.A_DIM)
    stdscr.refresh()
    stdscr.getch()
    stdscr.nodelay(True)


def show_translator(stdscr, world, lang):
    """A frozen snapshot - what each color means right now, inverted from
    the HUD's state->color view into a color->state dictionary. Opened like
    show_help()/show_graph(); no history, just this instant."""
    t = TEXT[lang]
    labels = STATE_LABELS[lang]
    stdscr.nodelay(False)
    stdscr.erase()

    _safe_addstr(stdscr, 0, 0, t["translator_title"], curses.color_pair(7) | curses.A_BOLD)

    by_token = world.translator()
    y = 2
    for token in range(N_TOKENS):
        if token == 0:
            _safe_addstr(stdscr, y, 0, "..", curses.color_pair(7) | curses.A_DIM)
        else:
            _safe_addstr(stdscr, y, 0, "##", curses.color_pair(TOKEN_COLOR_PAIR[token]) | curses.A_BOLD)
        claims = by_token[token]
        if claims:
            text = " / ".join(f"{labels[state]} ({frac * 100:.0f}%)" for state, frac in claims)
        else:
            text = t["translator_unused"]
        _safe_addstr(stdscr, y, 3, text, curses.color_pair(7))
        y += 1
        if len(claims) > 1:
            _safe_addstr(stdscr, y, 0, t["translator_homonym"], curses.color_pair(1))
            y += 1

    _safe_addstr(stdscr, y + 1, 0, t["translator_dismiss"], curses.color_pair(7) | curses.A_DIM)
    stdscr.refresh()
    stdscr.getch()
    stdscr.nodelay(True)


def _family_short_label(world, cid):
    rec = world.lineage.get(cid)
    if rec is None:
        return f"#{cid}"
    if rec["death"] is None:
        return f"#{cid} (gen {rec['gen']}, alive)"
    return f"#{cid} (gen {rec['gen']}, dead t{rec['death']})"


def show_family(stdscr, world, lang):
    """An ego-centric genealogy browser, opened like show_graph()/show_help():
    one creature in focus at a time, arrow keys walk the tree (parent above,
    first child below, siblings sideways) instead of trying to cram a whole
    population's tree onto one screen."""
    t = TEXT[lang]
    stdscr.nodelay(False)
    focus = world.default_family_focus()
    if focus is None:
        stdscr.erase()
        _safe_addstr(stdscr, 0, 0, t["family_none"], curses.color_pair(7) | curses.A_BOLD)
        _safe_addstr(stdscr, 2, 0, t["family_dismiss"], curses.color_pair(7) | curses.A_DIM)
        stdscr.refresh()
        stdscr.getch()
        stdscr.nodelay(True)
        return

    while True:
        info = world.family_info(focus)
        stdscr.erase()
        _safe_addstr(stdscr, 0, 0, t["family_title"], curses.color_pair(7) | curses.A_BOLD)

        y = 2
        _safe_addstr(stdscr, y, 0, f"#{info['id']}  {t['family_gen'].format(gen=info['gen'])}",
                     curses.color_pair(7) | curses.A_BOLD)
        y += 1
        status = (t["family_alive"].format(token=info["token"], age=info["age"]) if info["alive"]
                  else t["family_dead"].format(death=info["death"]))
        pair = TOKEN_COLOR_PAIR.get(info["token"], 7) if info["alive"] else 7
        _safe_addstr(stdscr, y, 0, status, curses.color_pair(pair))
        y += 1
        _safe_addstr(stdscr, y, 0, t["family_born"].format(tick=info["birth"]), curses.color_pair(7) | curses.A_DIM)
        y += 2

        _safe_addstr(stdscr, y, 0, t["family_parents"], curses.color_pair(7) | curses.A_BOLD)
        y += 1
        if info["parents"]:
            for pid in info["parents"]:
                _safe_addstr(stdscr, y, 2, _family_short_label(world, pid), curses.color_pair(7))
                y += 1
        else:
            _safe_addstr(stdscr, y, 2, t["family_founder"], curses.color_pair(7) | curses.A_DIM)
            y += 1
        y += 1

        _safe_addstr(stdscr, y, 0, t["family_children"].format(n=len(info["children"])),
                     curses.color_pair(7) | curses.A_BOLD)
        y += 1
        if info["children"]:
            for cid in info["children"][:8]:
                _safe_addstr(stdscr, y, 2, _family_short_label(world, cid), curses.color_pair(7))
                y += 1
            if len(info["children"]) > 8:
                _safe_addstr(stdscr, y, 2, f"... +{len(info['children']) - 8}", curses.color_pair(7) | curses.A_DIM)
                y += 1
        else:
            _safe_addstr(stdscr, y, 2, t["family_no_children"], curses.color_pair(7) | curses.A_DIM)
            y += 1
        y += 1

        _safe_addstr(stdscr, y, 0,
                     t["family_descendants"].format(total=info["total_descendants"], alive=info["alive_descendants"]),
                     curses.color_pair(7))
        y += 2
        _safe_addstr(stdscr, y, 0, t["family_hint"], curses.color_pair(7) | curses.A_DIM)
        stdscr.refresh()

        key = stdscr.getch()
        if key in (27, ord("t"), ord("T")):
            break
        elif key == curses.KEY_UP and info["parents"]:
            focus = info["parents"][0]
        elif key == curses.KEY_DOWN and info["children"]:
            focus = info["children"][0]
        elif key in (curses.KEY_LEFT, curses.KEY_RIGHT) and info["parents"]:
            siblings = world.family_info(info["parents"][0])["children"]
            if focus in siblings and len(siblings) > 1:
                i = siblings.index(focus)
                i = (i + (1 if key == curses.KEY_RIGHT else -1)) % len(siblings)
                focus = siblings[i]

    stdscr.nodelay(True)


COMPARE_QUICK = (4, 8000)
COMPARE_THOROUGH = (8, 40000)
COMPARE_EXPERT = (16, 60000)


def choose_compare_mode(stdscr, lang, traits_available):
    t = TEXT[lang]
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        (t["compare_mode_prompt"], curses.A_BOLD),
        (t["compare_mode_language"], 0),
        (t["compare_mode_traits"] if traits_available else t["compare_mode_traits_unavailable"], 0),
        ("", 0),
        (t["compare_mode_hint"], curses.A_DIM),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    stdscr.refresh()

    mode = None
    while mode is None:
        key = stdscr.getch()
        if key in (ord("l"), ord("L")):
            mode = "language"
        elif key in (ord("t"), ord("T")) and traits_available:
            mode = "traits"
        elif key == 27:
            stdscr.nodelay(True)
            return None
    stdscr.nodelay(True)
    return mode


def choose_compare_depth(stdscr, lang):
    t = TEXT[lang]
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        (t["compare_depth_prompt"], curses.A_BOLD),
        (t["compare_depth_quick"], 0),
        (t["compare_depth_thorough"], 0),
        (t["compare_depth_expert"], 0),
        ("", 0),
        (t["compare_depth_hint"], curses.A_DIM),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    stdscr.refresh()

    depth = None
    while depth is None:
        key = stdscr.getch()
        if key in (ord("r"), ord("R")) or key in ENTER_KEYS:
            depth = COMPARE_QUICK
        elif key in (ord("a"), ord("A")):
            depth = COMPARE_THOROUGH
        elif key in (ord("e"), ord("E")):
            depth = COMPARE_EXPERT
        elif key == 27:
            stdscr.nodelay(True)
            return None
    stdscr.nodelay(True)
    return depth


def run_compare_ui(stdscr, world, lang, init_pop, seed_genome):
    """Curses equivalent of main.py's Compare screen. No real threading
    needed here - curses is already a blocking single loop, so the batch
    just runs directly, with progress_callback redrawing the screen and
    polling for ESC every 200 ticks (compare_seeds()'s own cadence)."""
    t = TEXT[lang]
    labels = STATE_LABELS[lang]
    trait_labels = TRAIT_LABELS[lang]

    mode = choose_compare_mode(stdscr, lang, world.adaptive_traits)
    if mode is None:
        return
    depth = choose_compare_depth(stdscr, lang)
    if depth is None:
        return
    n_seeds, ticks = depth

    cancel_event = threading.Event()
    stdscr.nodelay(True)

    def on_progress(seed_i, n, tick, total_ticks):
        key = stdscr.getch()
        if key == 27:
            cancel_event.set()
        stdscr.erase()
        _safe_addstr(stdscr, 0, 0,
                     t["compare_progress"].format(seed=seed_i + 1, n_seeds=n_seeds, tick=tick, ticks=ticks),
                     curses.color_pair(7) | curses.A_BOLD)
        stdscr.refresh()

    results = compare_seeds(n_seeds, ticks, init_pop, len(world.predators), mode == "traits",
                             seed_genome=seed_genome, progress_callback=on_progress, cancel_event=cancel_event)

    cancelled = cancel_event.is_set()
    if cancelled and not results:
        stdscr.nodelay(False)
        stdscr.erase()
        _safe_addstr(stdscr, 0, 0, t["compare_cancelled"].format(n=len(results)),
                     curses.color_pair(1) | curses.A_BOLD)
        stdscr.refresh()
        stdscr.getch()
        stdscr.nodelay(True)
        return

    stdscr.nodelay(False)
    stdscr.erase()
    y = 0
    _safe_addstr(stdscr, y, 0, t["compare_result_title"].format(n_seeds=len(results), ticks=ticks),
                 curses.color_pair(7) | curses.A_BOLD)
    y += 2

    if mode == "traits":
        _safe_addstr(stdscr, y, 0, t["compare_traits_header"], curses.color_pair(7) | curses.A_BOLD)
        y += 1
        for trait in range(N_TRAITS):
            vals = [r["traits"][trait] * 100 for r in results if r["traits"] is not None]
            mean = sum(vals) / len(vals)
            std = (sum((v - mean) ** 2 for v in vals) / len(vals)) ** 0.5
            row = f"{trait_labels[trait]:<14} {mean:5.1f}%   {std:5.1f}%   {min(vals):5.1f}%  {max(vals):5.1f}%"
            _safe_addstr(stdscr, y, 0, row, curses.color_pair(7))
            y += 1
    else:
        _safe_addstr(stdscr, y, 0, t["compare_lang_header"], curses.color_pair(7) | curses.A_BOLD)
        y += 1
        for state in (DANGER, FOOD, DISTRESS, MATE, IDLE):
            x = 0
            _safe_addstr(stdscr, y, x, f"{labels[state]:<14}", curses.color_pair(7))
            x += 15
            for r in results:
                token = r["vocab"][state][0]
                if token == 0:
                    _safe_addstr(stdscr, y, x, "..", curses.color_pair(7) | curses.A_DIM)
                else:
                    _safe_addstr(stdscr, y, x, "##", curses.color_pair(TOKEN_COLOR_PAIR[token]) | curses.A_BOLD)
                x += 3
            y += 1
        y += 1
        clean = sum(1 for r in results if not r["collision"])
        _safe_addstr(stdscr, y, 0, t["compare_collision_summary"].format(clean=clean, n_seeds=len(results)),
                     curses.color_pair(7))
        y += 1

    if cancelled:
        y += 1
        _safe_addstr(stdscr, y, 0, t["compare_cancelled"].format(n=len(results)), curses.color_pair(1) | curses.A_BOLD)
        y += 1

    _safe_addstr(stdscr, y + 1, 0, t["compare_dismiss"], curses.color_pair(7) | curses.A_DIM)
    stdscr.refresh()
    stdscr.getch()
    stdscr.nodelay(True)


def choose_language(stdscr):
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        ("Choose your language / Choisis ta langue :", curses.A_BOLD),
        ("  E = English", 0),
        ("  F = Francais (defaut)", 0),
        ("", 0),
        ("Press E or F to continue, or ENTER for the default (Francais).", curses.A_DIM),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    stdscr.refresh()

    lang = None
    while lang is None:
        key = stdscr.getch()
        if key in (ord("e"), ord("E")):
            lang = "en"
        elif key in (ord("f"), ord("F")) or key in ENTER_KEYS:
            lang = "fr"
    stdscr.nodelay(True)
    return lang


def choose_mode(stdscr, lang):
    t = TEXT[lang]
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        (t["choose_mode_prompt"], curses.A_BOLD),
        (t["choose_mode_auto"], 0),
        (t["choose_mode_manual"], 0),
        ("", 0),
        (t["choose_mode_hint"], curses.A_DIM),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    stdscr.refresh()

    mode = None
    while mode is None:
        key = stdscr.getch()
        if key in (ord("a"), ord("A")) or key in ENTER_KEYS:
            mode = "auto"
        elif key in (ord("m"), ord("M")):
            mode = "manual"
    stdscr.nodelay(True)
    return mode


def choose_population(stdscr, lang):
    t = TEXT[lang]
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        (t["choose_pop_prompt"].format(max=MAX_POPULATION, default=DEFAULT_INIT_POP), curses.A_BOLD),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    _safe_addstr(stdscr, 4, 0, "> ", curses.color_pair(7))
    stdscr.refresh()

    curses.echo()
    curses.curs_set(1)
    text = stdscr.getstr(4, 2, 4).decode(errors="ignore").strip()
    curses.noecho()
    curses.curs_set(0)
    stdscr.nodelay(True)

    try:
        n = int(text)
    except ValueError:
        return DEFAULT_INIT_POP
    return max(1, min(MAX_POPULATION, n))


def choose_adaptive_traits(stdscr, lang):
    t = TEXT[lang]
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        (t["choose_traits_prompt"], curses.A_BOLD),
        (t["choose_traits_explain1"], 0),
        (t["choose_traits_explain2"], 0),
        ("", 0),
        (t["choose_traits_yes"], 0),
        (t["choose_traits_no"], 0),
        ("", 0),
        (t["choose_traits_hint"], curses.A_DIM),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    stdscr.refresh()

    yes_keys = (ord("o"), ord("O")) if lang == "fr" else (ord("y"), ord("Y"))
    choice = None
    while choice is None:
        key = stdscr.getch()
        if key in yes_keys:
            choice = True
        elif key in (ord("n"), ord("N")) or key in ENTER_KEYS:
            choice = False
    stdscr.nodelay(True)
    return choice


def choose_ai(stdscr, lang):
    t = TEXT[lang]
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        (t["choose_ai_prompt"], curses.A_BOLD),
        (t["choose_ai_subtitle"].format(file=DEFAULT_LANGUAGE_FILE), 0),
        ("", 0),
        (t["choose_ai_yes"], 0),
        (t["choose_ai_no"], 0),
        ("", 0),
        (t["choose_ai_hint"], curses.A_DIM),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    stdscr.refresh()

    yes_keys = (ord("o"), ord("O")) if lang == "fr" else (ord("y"), ord("Y"))
    choice = None
    while choice is None:
        key = stdscr.getch()
        if key in yes_keys or key in ENTER_KEYS:
            choice = True
        elif key in (ord("n"), ord("N")):
            choice = False
    stdscr.nodelay(True)
    return choice


def choose_resume(stdscr, lang):
    t = TEXT[lang]
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        (t["choose_resume_prompt"], curses.A_BOLD),
        (t["choose_resume_subtitle"].format(file=DEFAULT_SAVE_FILE), 0),
        ("", 0),
        (t["choose_resume_yes"], 0),
        (t["choose_resume_no"], 0),
        ("", 0),
        (t["choose_resume_hint"], curses.A_DIM),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    stdscr.refresh()

    yes_keys = (ord("o"), ord("O")) if lang == "fr" else (ord("y"), ord("Y"))
    choice = None
    while choice is None:
        key = stdscr.getch()
        if key in yes_keys:
            choice = True
        elif key in (ord("n"), ord("N")):
            choice = False
    stdscr.nodelay(True)
    return choice


def _flash_message(stdscr, lang, text):
    stdscr.nodelay(False)
    stdscr.erase()
    _safe_addstr(stdscr, 0, 0, text, curses.color_pair(1) | curses.A_BOLD)
    _safe_addstr(stdscr, 2, 0, TEXT[lang]["flash_hint"], curses.color_pair(7) | curses.A_DIM)
    stdscr.refresh()
    stdscr.getch()
    stdscr.nodelay(True)


def draw(stdscr, world, paused, speed, mode, placing, cursor, lang, trained=False):
    t = TEXT[lang]
    labels = STATE_LABELS[lang]
    stdscr.erase()
    rows, cols = stdscr.getmaxyx()
    field_h = max(1, rows - HUD_H)
    field_w = max(1, cols)
    sx, sy = (field_w - 1) / WIDTH, (field_h - 1) / HEIGHT

    pop = world.population()
    status = t["hud_paused"] if paused else f"x{speed}"
    tag = (t["hud_trained_tag"] if trained else "") + (t["hud_traits_tag"] if world.adaptive_traits else "")
    header = t["hud_header"].format(tick=world.tick, pop=pop, births=world.births,
                                     deaths=world.deaths, status=status, tag=tag)
    _safe_addstr(stdscr, 0, 0, header, curses.color_pair(7) | curses.A_BOLD)

    if mode == "manual":
        placing_label = t["placing_food"] if placing == "food" else t["placing_predator"]
        settings = t["hud_manual"].format(placing=placing_label)
    else:
        settings = t["hud_auto"].format(count=len(world.predators))
    _safe_addstr(stdscr, 1, 0, settings, curses.color_pair(7) | curses.A_DIM)

    breakdown = world.vocabulary_breakdown()
    for row, state in enumerate((DANGER, FOOD, DISTRESS, MATE, IDLE), start=2):
        _draw_vocab_row(stdscr, row, labels[state], breakdown[state])

    _safe_addstr(stdscr, HUD_H - 3, 0, t["hud_legend"], curses.color_pair(7) | curses.A_DIM)
    _safe_addstr(stdscr, HUD_H - 2, 0, t["hud_controls1"], curses.color_pair(7) | curses.A_DIM)
    _safe_addstr(stdscr, HUD_H - 1, 0, t["hud_controls2"], curses.color_pair(7) | curses.A_DIM)

    for fx, fy in world.food:
        y, x = HUD_H + int(fy * sy), int(fx * sx)
        _safe_addstr(stdscr, y, x, ".", curses.color_pair(6))

    for c in world.creatures:
        if not c.alive:
            continue
        y, x = HUD_H + int(c.pos[1] * sy), int(c.pos[0] * sx)
        pair = TOKEN_COLOR_PAIR.get(c.token, 7)
        _safe_addstr(stdscr, y, x, "o", curses.color_pair(pair) | curses.A_BOLD)

    for p in world.predators:
        y, x = HUD_H + int(p.pos[1] * sy), int(p.pos[0] * sx)
        _safe_addstr(stdscr, y, x, "X", curses.color_pair(1) | curses.A_BOLD)

    if mode == "manual":
        cy, cx = HUD_H + int(cursor[1] * sy), int(cursor[0] * sx)
        pair = 6 if placing == "food" else 1
        _safe_addstr(stdscr, cy, cx, "+", curses.color_pair(pair) | curses.A_BOLD | curses.A_REVERSE)

    if pop == 0:
        _safe_addstr(stdscr, HUD_H + field_h // 2, max(0, cols // 2 - 12),
                     t["extinct"], curses.color_pair(1) | curses.A_BOLD)

    stdscr.refresh()


def _new_world(mode, predator_count, init_pop=DEFAULT_INIT_POP, seed_genome=None, adaptive_traits=False):
    if mode == "manual":
        return World(init_pop=init_pop, manual_food=True, manual_predators=True,
                      seed_genome=seed_genome, adaptive_traits=adaptive_traits)
    return World(init_pop=init_pop, predator_count=predator_count,
                 seed_genome=seed_genome, adaptive_traits=adaptive_traits)


def run(stdscr, language_path=None):
    curses.curs_set(0)
    setup_colors()

    lang = choose_language(stdscr)

    world = None
    if os.path.exists(DEFAULT_SAVE_FILE) and choose_resume(stdscr, lang):
        try:
            world = load_world(DEFAULT_SAVE_FILE)
            mode = "manual" if (world.manual_food or world.manual_predators) else "auto"
            init_pop = world.population()
        except (OSError, ValueError, KeyError):
            world = None
            _flash_message(stdscr, lang, TEXT[lang]["resume_load_failed"].format(file=DEFAULT_SAVE_FILE))

    seed_genome = None
    if world is None:
        mode = choose_mode(stdscr, lang)
        init_pop = choose_population(stdscr, lang)
        adaptive_traits = choose_adaptive_traits(stdscr, lang)

        if language_path:
            seed_genome = load_seed_genome(language_path)
        elif choose_ai(stdscr, lang):
            try:
                seed_genome = load_seed_genome(DEFAULT_LANGUAGE_FILE)
            except OSError:
                seed_genome = None
                _flash_message(stdscr, lang, TEXT[lang]["ai_missing_file"].format(file=DEFAULT_LANGUAGE_FILE))
        world = _new_world(mode, 6, init_pop, seed_genome, adaptive_traits)
    else:
        adaptive_traits = world.adaptive_traits

    placing = "food"
    cursor = [WIDTH / 2, HEIGHT / 2]

    paused = False
    speed = 1  # ticks per real second
    frame_time = 1 / 20
    tick_accumulator = 0.0

    while True:
        key = stdscr.getch()
        if key in (ord("q"), 27):
            break
        elif key == ord(" "):
            paused = not paused
        elif key == ord("r"):
            world = _new_world(mode, len(world.predators), init_pop, seed_genome, adaptive_traits)
        elif key in (ord("+"), ord("=")):
            speed = min(200, speed + (1 if speed < 10 else 10))
        elif key in (ord("-"), ord("_")):
            speed = max(1, speed - (1 if speed <= 10 else 10))
        elif key == ord("n"):
            world.add_food(*world.rng.uniform([10, 10], [WIDTH - 10, HEIGHT - 10]))
        elif key == ord("p"):
            world.add_random_predator()
        elif key == 9:  # Tab - switch what arrows+enter places
            placing = "predator" if placing == "food" else "food"
        elif key == ord("["):
            world.remove_predator()
        elif key == ord("]"):
            world.add_random_predator()
        elif key == ord("s"):
            save_world(world, DEFAULT_SAVE_FILE)
            _flash_message(stdscr, lang, TEXT[lang]["save_confirmed"].format(file=DEFAULT_SAVE_FILE))
        elif key == ord("g"):
            show_graph(stdscr, world, lang)
        elif key == ord("t"):
            show_family(stdscr, world, lang)
        elif key == ord("c"):
            run_compare_ui(stdscr, world, lang, init_pop, seed_genome)
        elif key == ord("d"):
            show_translator(stdscr, world, lang)
        elif key == ord("F"):
            show_faq(stdscr, lang)
        elif key == ord("h"):
            show_help(stdscr, lang)
        elif key == curses.KEY_UP:
            cursor[1] = max(0.0, cursor[1] - CURSOR_STEP)
        elif key == curses.KEY_DOWN:
            cursor[1] = min(HEIGHT, cursor[1] + CURSOR_STEP)
        elif key == curses.KEY_LEFT:
            cursor[0] = max(0.0, cursor[0] - CURSOR_STEP)
        elif key == curses.KEY_RIGHT:
            cursor[0] = min(WIDTH, cursor[0] + CURSOR_STEP)
        elif key in ENTER_KEYS and mode == "manual":
            if placing == "food":
                world.add_food(cursor[0], cursor[1])
            else:
                world.add_predator(cursor[0], cursor[1])

        if not paused:
            tick_accumulator += frame_time
            tick_interval = 1.0 / speed
            while tick_accumulator >= tick_interval:
                world.step()
                tick_accumulator -= tick_interval
        else:
            tick_accumulator = 0.0

        draw(stdscr, world, paused, speed, mode, placing, cursor, lang, trained=seed_genome is not None)
        time.sleep(frame_time)


def main():
    parser = argparse.ArgumentParser(description="Thronglets - terminal renderer")
    parser.add_argument("--language", type=str, default=None,
                         help="seed the population with a train_language.py --export vocabulary "
                              "instead of starting from scratch")
    args = parser.parse_args()

    curses.wrapper(run, args.language)


if __name__ == "__main__":
    main()
