"""Terminal (curses) renderer for Thronglets.

No GUI/X11/SDL needed - handy on Termux or over plain SSH, where pygame is
painful to install. Only the Python standard library plus numpy are needed.

You pick a language, automatic or manual mode, and whether to seed the AI
language once, at startup - not something you toggle mid-run.

Controls: space=pause  f=drop food (auto mode only)  r=reset  +/-=speed  q=quit
  p=toggle food/predator (manual placement)
  [ / ]=remove/add a predator right now (also sets the count used on reset)
  arrow keys=move cursor, enter=place (manual mode)
  h=in-game notice/help screen
"""

import argparse
import curses
import os
import time

from i18n import STATE_LABELS
from simulation import (DANGER, DISTRESS, FOOD, HEIGHT, IDLE, MATE, MAX_POPULATION, World, WIDTH,
                         load_seed_genome, load_world, save_world)

DEFAULT_INIT_POP = 100
DEFAULT_LANGUAGE_FILE = "language_model.json"
DEFAULT_SAVE_FILE = "thronglets_save.json"

TOKEN_COLOR_PAIR = {1: 1, 2: 2, 3: 3, 4: 4, 5: 5}
HUD_H = 10
CURSOR_STEP = 4.0
ENTER_KEYS = (10, 13, curses.KEY_ENTER)

TEXT = {
    "en": {
        "choose_mode_prompt": "Choose the starting mode:",
        "choose_mode_auto": "  A = automatic - food and predators spawn on their own (default)",
        "choose_mode_manual": "  M = manual - you place everything yourself, nothing spawns alone",
        "choose_mode_hint": "Press A or M, or ENTER for the default (automatic).",

        "choose_pop_prompt": "How many creatures to start with? (1-{max}, enter = {default})",

        "choose_ai_prompt": "Activate the pre-trained AI language?",
        "choose_ai_subtitle": "  (reads '{file}', generated by train_language.py)",
        "choose_ai_yes": "  Y = yes - creatures already speak an unambiguous language (default)",
        "choose_ai_no": "  N = no - the language has to emerge on its own while you play",
        "choose_ai_hint": "Press Y or N, or ENTER for the default (yes).",
        "ai_missing_file": "'{file}' not found - starting without AI.",
        "flash_hint": "-- press any key to continue --",

        "choose_resume_prompt": "A saved game was found. Resume it?",
        "choose_resume_subtitle": "  (reads '{file}' - the population, food, and predators as you left them)",
        "choose_resume_yes": "  Y = yes - pick up exactly where you left off",
        "choose_resume_no": "  N = no - start a fresh game instead",
        "choose_resume_hint": "Press Y or N to continue.",
        "resume_load_failed": "'{file}' could not be read - starting a fresh game instead.",
        "save_confirmed": "Game saved to '{file}'.",

        "hud_paused": "PAUSED",
        "hud_trained_tag": "  [trained vocabulary]",
        "hud_header": "tick {tick}  pop {pop}  births {births}  deaths {deaths}  {status}{tag}",
        "hud_manual": "mode: manual   placing: {placing} (p)   arrows+enter to place",
        "hud_auto": "mode: automatic   predators: {count} ([ ] act immediately)",
        "placing_food": "food",
        "placing_predator": "predator",
        "hud_legend": "colored o = signaling   white o = silent   . = food   X = predator",
        "hud_controls1": "space=pause  {food_hint}  r=reset  +/-=speed  q=quit",
        "food_hint_auto": "f=food",
        "food_hint_manual": "f=food (auto mode only)",
        "hud_controls2": "p=place  [ ]=predator count  s=save  arrows/enter=place  h=help",
        "extinct": "Extinct. Press r to reset.",

        "help_more": "-- space for more --",
        "help_dismiss": "-- press any key to resume --",
    },
    "fr": {
        "choose_mode_prompt": "Choisis le mode de depart :",
        "choose_mode_auto": "  A = automatique - nourriture et predateurs apparaissent seuls (defaut)",
        "choose_mode_manual": "  M = manuel - tu places tout toi-meme, rien ne spawn seul",
        "choose_mode_hint": "Appuie sur A ou M, ou ENTREE pour le defaut (auto).",

        "choose_pop_prompt": "Combien de creatures au depart ? (1-{max}, entree = {default})",

        "choose_ai_prompt": "Activer le langage pre-entraine par IA ?",
        "choose_ai_subtitle": "  (relit '{file}', genere par train_language.py)",
        "choose_ai_yes": "  O = oui - les creatures parlent deja un langage sans confusion (defaut)",
        "choose_ai_no": "  N = non - le langage doit emerger tout seul en jouant",
        "choose_ai_hint": "Appuie sur O ou N, ou ENTREE pour le defaut (oui).",
        "ai_missing_file": "'{file}' introuvable - lancement sans IA.",
        "flash_hint": "-- une touche pour continuer --",

        "choose_resume_prompt": "Une partie sauvegardee existe. La reprendre ?",
        "choose_resume_subtitle": "  (relit '{file}' - la population, la nourriture et les predateurs tels que laisses)",
        "choose_resume_yes": "  O = oui - reprendre exactement ou tu t'es arrete",
        "choose_resume_no": "  N = non - commencer une nouvelle partie",
        "choose_resume_hint": "Appuie sur O ou N pour continuer.",
        "resume_load_failed": "'{file}' illisible - nouvelle partie a la place.",
        "save_confirmed": "Partie sauvegardee dans '{file}'.",

        "hud_paused": "PAUSE",
        "hud_trained_tag": "  [vocabulaire entraine]",
        "hud_header": "tick {tick}  pop {pop}  naissances {births}  morts {deaths}  {status}{tag}",
        "hud_manual": "mode: manuel   pose: {placing} (p)   fleches+entree pour placer",
        "hud_auto": "mode: auto   predateurs: {count} ([ ] agit tout de suite)",
        "placing_food": "nourriture",
        "placing_predator": "predateur",
        "hud_legend": "o colore = signale   o blanc = silencieuse   . = nourriture   X = predateur",
        "hud_controls1": "space=pause  {food_hint}  r=reset  +/-=speed  q=quit",
        "food_hint_auto": "f=food",
        "food_hint_manual": "f=food (auto uniquement)",
        "hud_controls2": "p=placer  [ ]=nb predateurs  s=sauver  fleches/entree=placer  h=aide",
        "extinct": "Extinction. Appuie sur r pour recommencer.",

        "help_more": "-- espace pour la suite --",
        "help_dismiss": "-- une touche pour reprendre --",
    },
}

HELP_LINES = {
    "en": [
        ("Thronglets - notice", curses.A_BOLD),
        ("", 0),
        ("Each creature is born with a genome deciding which color it shows", 0),
        ("for its current state, and how it reacts to colors it hears from", 0),
        ("others. Nobody programs what a color means - a shared language can", 0),
        ("emerge through natural selection, or it might not.", 0),
        ("", 0),
        ("The 5 states, in priority order:", curses.A_BOLD),
        ("  1. alarm-call    a predator was spotted -> flee immediately", 0),
        ("  2. food-call     food is visible nearby", 0),
        ("  3. distress-call energy critically low, no food in sight", 0),
        ("  4. mate-call     ready to mate, and a ready partner is nearby", 0),
        ("  5. idle          nothing special (by far the most common state)", 0),
        ("", 0),
        ("Living, mating, dying:", curses.A_BOLD),
        ("  Energy drains constantly; eating restores it. Emitting a color", 0),
        ("  (other than silence) costs a bit of extra energy. Enough energy", 0),
        ("  and age, plus a matching partner nearby: a child is born. A", 0),
        ("  predator that catches a creature kills it outright.", 0),
        ("", 0),
        ("Reading the vocabulary rows at the top:", curses.A_BOLD),
        ("  For each state, the share of the population using each color.", 0),
        ("  It starts near chance (~17%) and climbs if a token wins out.", 0),
        ("  A '..' swatch means silence, not a missing color.", 0),
        ("", 0),
        ("Worth knowing:", curses.A_BOLD),
        ("  Two states can end up sharing the same color purely by chance", 0),
        ("  (e.g. idle and alarm-call) - nothing prevents it or guarantees", 0),
        ("  it resolves. Signaling costs energy, so silence is a real", 0),
        ("  strategy, not a default.", 0),
    ],
    "fr": [
        ("Thronglets — notice", curses.A_BOLD),
        ("", 0),
        ("Chaque creature nait avec un genome qui decide quelle couleur", 0),
        ("elle affiche selon son etat, et comment elle reagit aux couleurs", 0),
        ("des autres. Personne ne programme le sens des couleurs : un", 0),
        ("langage commun peut emerger par selection naturelle, ou pas.", 0),
        ("", 0),
        ("Les 5 etats, par ordre de priorite :", curses.A_BOLD),
        ("  1. alerte     un predateur repere -> fuite immediate", 0),
        ("  2. nourriture de la nourriture est visible tout pres", 0),
        ("  3. detresse   energie tres basse, aucune nourriture en vue", 0),
        ("  4. partenaire prete a se reproduire + partenaire prete proche", 0),
        ("  5. inactif    rien de special (etat le plus frequent, de loin)", 0),
        ("", 0),
        ("Vivre, se reproduire, mourir :", curses.A_BOLD),
        ("  L'energie baisse en permanence, manger la restaure. Emettre", 0),
        ("  une couleur (hors silence) coute un peu d'energie en plus.", 0),
        ("  Assez d'energie et d'age, un partenaire pareil a proximite :", 0),
        ("  un enfant nait. Un predateur qui attrape une creature la tue.", 0),
        ("", 0),
        ("Lire le vocabulaire affiche en haut :", curses.A_BOLD),
        ("  Pour chaque etat, la part de la population qui utilise chaque", 0),
        ("  couleur. Ca part du hasard (~17%) et grimpe si un mot fait", 0),
        ("  consensus. '..' = silence, pas une couleur en moins.", 0),
        ("", 0),
        ("A savoir :", curses.A_BOLD),
        ("  Deux etats peuvent finir sur la meme couleur par hasard (ex:", 0),
        ("  inactif et alerte) - rien ne l'empeche ni ne garantit que ca", 0),
        ("  se resolve. Parler coute de l'energie : le silence est une", 0),
        ("  vraie strategie, pas un defaut.", 0),
    ],
}


def show_help(stdscr, lang):
    """Paginate so this fits any terminal height, not just tall ones."""
    stdscr.nodelay(False)
    rows, _ = stdscr.getmaxyx()
    lines = HELP_LINES[lang]
    page_size = max(1, rows - 2)
    for start in range(0, len(lines), page_size):
        page = lines[start:start + page_size]
        stdscr.erase()
        for i, (line, attr) in enumerate(page):
            _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
        more = start + page_size < len(lines)
        footer = TEXT[lang]["help_more"] if more else TEXT[lang]["help_dismiss"]
        _safe_addstr(stdscr, min(rows - 1, len(page) + 1), 0, footer, curses.color_pair(7) | curses.A_DIM)
        stdscr.refresh()
        stdscr.getch()
    stdscr.nodelay(True)


def setup_colors():
    curses.start_color()
    curses.use_default_colors()
    curses.init_pair(1, curses.COLOR_RED, -1)
    curses.init_pair(2, curses.COLOR_BLUE, -1)
    curses.init_pair(3, curses.COLOR_YELLOW, -1)
    curses.init_pair(4, curses.COLOR_MAGENTA, -1)
    curses.init_pair(5, curses.COLOR_CYAN, -1)
    curses.init_pair(6, curses.COLOR_GREEN, -1)   # food
    curses.init_pair(7, curses.COLOR_WHITE, -1)   # hud / body


def _safe_addstr(stdscr, y, x, text, attr):
    rows, cols = stdscr.getmaxyx()
    if 0 <= y < rows and 0 <= x < cols:
        try:
            stdscr.addstr(y, x, text[: cols - x], attr)
        except curses.error:
            pass


SPARK_CHARS = " ▁▂▃▄▅▆▇█"  # blank + 8 block levels


def _sparkline(history, width=24):
    if not history:
        return SPARK_CHARS[0] * width
    values = list(history)[-width:]
    values = [SPARK_CHARS[0]] * (width - len(values)) + [
        SPARK_CHARS[1 + min(7, int(v * 8))] for v in values
    ]
    return "".join(values)


def _draw_vocab_row(stdscr, y, label, pairs, history=None):
    x = 0
    _safe_addstr(stdscr, y, x, f"{label}:", curses.color_pair(7) | curses.A_BOLD)
    x += len(label) + 2
    for token, frac in pairs:
        if token == 0:
            _safe_addstr(stdscr, y, x, "..", curses.color_pair(7) | curses.A_DIM)
        else:
            _safe_addstr(stdscr, y, x, "##", curses.color_pair(TOKEN_COLOR_PAIR[token]) | curses.A_BOLD)
        seg = f"{frac * 100:3.0f}% "
        _safe_addstr(stdscr, y, x + 2, seg, curses.color_pair(7))
        x += 2 + len(seg)
    if history is not None:
        _safe_addstr(stdscr, y, x + 2, _sparkline(history), curses.color_pair(7) | curses.A_DIM)


def choose_language(stdscr):
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        ("Choose your language / Choisis ta langue :", curses.A_BOLD),
        ("  E = English", 0),
        ("  F = Francais (defaut)", 0),
        ("", 0),
        ("Press E or F to continue, or ENTER for the default (Francais).", curses.A_DIM),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    stdscr.refresh()

    lang = None
    while lang is None:
        key = stdscr.getch()
        if key in (ord("e"), ord("E")):
            lang = "en"
        elif key in (ord("f"), ord("F")) or key in ENTER_KEYS:
            lang = "fr"
    stdscr.nodelay(True)
    return lang


def choose_mode(stdscr, lang):
    t = TEXT[lang]
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        (t["choose_mode_prompt"], curses.A_BOLD),
        (t["choose_mode_auto"], 0),
        (t["choose_mode_manual"], 0),
        ("", 0),
        (t["choose_mode_hint"], curses.A_DIM),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    stdscr.refresh()

    mode = None
    while mode is None:
        key = stdscr.getch()
        if key in (ord("a"), ord("A")) or key in ENTER_KEYS:
            mode = "auto"
        elif key in (ord("m"), ord("M")):
            mode = "manual"
    stdscr.nodelay(True)
    return mode


def choose_population(stdscr, lang):
    t = TEXT[lang]
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        (t["choose_pop_prompt"].format(max=MAX_POPULATION, default=DEFAULT_INIT_POP), curses.A_BOLD),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    _safe_addstr(stdscr, 4, 0, "> ", curses.color_pair(7))
    stdscr.refresh()

    curses.echo()
    curses.curs_set(1)
    text = stdscr.getstr(4, 2, 4).decode(errors="ignore").strip()
    curses.noecho()
    curses.curs_set(0)
    stdscr.nodelay(True)

    try:
        n = int(text)
    except ValueError:
        return DEFAULT_INIT_POP
    return max(1, min(MAX_POPULATION, n))


def choose_ai(stdscr, lang):
    t = TEXT[lang]
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        (t["choose_ai_prompt"], curses.A_BOLD),
        (t["choose_ai_subtitle"].format(file=DEFAULT_LANGUAGE_FILE), 0),
        ("", 0),
        (t["choose_ai_yes"], 0),
        (t["choose_ai_no"], 0),
        ("", 0),
        (t["choose_ai_hint"], curses.A_DIM),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    stdscr.refresh()

    yes_keys = (ord("o"), ord("O")) if lang == "fr" else (ord("y"), ord("Y"))
    choice = None
    while choice is None:
        key = stdscr.getch()
        if key in yes_keys or key in ENTER_KEYS:
            choice = True
        elif key in (ord("n"), ord("N")):
            choice = False
    stdscr.nodelay(True)
    return choice


def choose_resume(stdscr, lang):
    t = TEXT[lang]
    stdscr.nodelay(False)
    stdscr.erase()
    lines = [
        ("Thronglets", curses.A_BOLD),
        ("", 0),
        (t["choose_resume_prompt"], curses.A_BOLD),
        (t["choose_resume_subtitle"].format(file=DEFAULT_SAVE_FILE), 0),
        ("", 0),
        (t["choose_resume_yes"], 0),
        (t["choose_resume_no"], 0),
        ("", 0),
        (t["choose_resume_hint"], curses.A_DIM),
    ]
    for i, (line, attr) in enumerate(lines):
        _safe_addstr(stdscr, i, 0, line, curses.color_pair(7) | attr)
    stdscr.refresh()

    yes_keys = (ord("o"), ord("O")) if lang == "fr" else (ord("y"), ord("Y"))
    choice = None
    while choice is None:
        key = stdscr.getch()
        if key in yes_keys:
            choice = True
        elif key in (ord("n"), ord("N")):
            choice = False
    stdscr.nodelay(True)
    return choice


def _flash_message(stdscr, lang, text):
    stdscr.nodelay(False)
    stdscr.erase()
    _safe_addstr(stdscr, 0, 0, text, curses.color_pair(1) | curses.A_BOLD)
    _safe_addstr(stdscr, 2, 0, TEXT[lang]["flash_hint"], curses.color_pair(7) | curses.A_DIM)
    stdscr.refresh()
    stdscr.getch()
    stdscr.nodelay(True)


def draw(stdscr, world, paused, speed, mode, placing, cursor, lang, trained=False):
    t = TEXT[lang]
    labels = STATE_LABELS[lang]
    stdscr.erase()
    rows, cols = stdscr.getmaxyx()
    field_h = max(1, rows - HUD_H)
    field_w = max(1, cols)
    sx, sy = (field_w - 1) / WIDTH, (field_h - 1) / HEIGHT

    pop = world.population()
    status = t["hud_paused"] if paused else f"x{speed}"
    tag = t["hud_trained_tag"] if trained else ""
    header = t["hud_header"].format(tick=world.tick, pop=pop, births=world.births,
                                     deaths=world.deaths, status=status, tag=tag)
    _safe_addstr(stdscr, 0, 0, header, curses.color_pair(7) | curses.A_BOLD)

    if mode == "manual":
        placing_label = t["placing_food"] if placing == "food" else t["placing_predator"]
        settings = t["hud_manual"].format(placing=placing_label)
    else:
        settings = t["hud_auto"].format(count=len(world.predators))
    _safe_addstr(stdscr, 1, 0, settings, curses.color_pair(7) | curses.A_DIM)

    breakdown = world.vocabulary_breakdown()
    for row, state in enumerate((DANGER, FOOD, DISTRESS, MATE, IDLE), start=2):
        _draw_vocab_row(stdscr, row, labels[state], breakdown[state], world.vocab_history[state])

    _safe_addstr(stdscr, HUD_H - 3, 0, t["hud_legend"], curses.color_pair(7) | curses.A_DIM)
    food_hint = t["food_hint_auto"] if mode == "auto" else t["food_hint_manual"]
    _safe_addstr(stdscr, HUD_H - 2, 0, t["hud_controls1"].format(food_hint=food_hint),
                 curses.color_pair(7) | curses.A_DIM)
    _safe_addstr(stdscr, HUD_H - 1, 0, t["hud_controls2"], curses.color_pair(7) | curses.A_DIM)

    for fx, fy in world.food:
        y, x = HUD_H + int(fy * sy), int(fx * sx)
        _safe_addstr(stdscr, y, x, ".", curses.color_pair(6))

    for c in world.creatures:
        if not c.alive:
            continue
        y, x = HUD_H + int(c.pos[1] * sy), int(c.pos[0] * sx)
        pair = TOKEN_COLOR_PAIR.get(c.token, 7)
        _safe_addstr(stdscr, y, x, "o", curses.color_pair(pair) | curses.A_BOLD)

    for p in world.predators:
        y, x = HUD_H + int(p.pos[1] * sy), int(p.pos[0] * sx)
        _safe_addstr(stdscr, y, x, "X", curses.color_pair(1) | curses.A_BOLD)

    if mode == "manual":
        cy, cx = HUD_H + int(cursor[1] * sy), int(cursor[0] * sx)
        pair = 6 if placing == "food" else 1
        _safe_addstr(stdscr, cy, cx, "+", curses.color_pair(pair) | curses.A_BOLD | curses.A_REVERSE)

    if pop == 0:
        _safe_addstr(stdscr, HUD_H + field_h // 2, max(0, cols // 2 - 12),
                     t["extinct"], curses.color_pair(1) | curses.A_BOLD)

    stdscr.refresh()


def _new_world(mode, predator_count, init_pop=DEFAULT_INIT_POP, seed_genome=None):
    if mode == "manual":
        return World(init_pop=init_pop, manual_food=True, manual_predators=True, seed_genome=seed_genome)
    return World(init_pop=init_pop, predator_count=predator_count, seed_genome=seed_genome)


def run(stdscr, language_path=None):
    curses.curs_set(0)
    setup_colors()

    lang = choose_language(stdscr)

    world = None
    if os.path.exists(DEFAULT_SAVE_FILE) and choose_resume(stdscr, lang):
        try:
            world = load_world(DEFAULT_SAVE_FILE)
            mode = "manual" if (world.manual_food or world.manual_predators) else "auto"
            init_pop = world.population()
        except (OSError, ValueError, KeyError):
            world = None
            _flash_message(stdscr, lang, TEXT[lang]["resume_load_failed"].format(file=DEFAULT_SAVE_FILE))

    seed_genome = None
    if world is None:
        mode = choose_mode(stdscr, lang)
        init_pop = choose_population(stdscr, lang)

        if language_path:
            seed_genome = load_seed_genome(language_path)
        elif choose_ai(stdscr, lang):
            try:
                seed_genome = load_seed_genome(DEFAULT_LANGUAGE_FILE)
            except OSError:
                seed_genome = None
                _flash_message(stdscr, lang, TEXT[lang]["ai_missing_file"].format(file=DEFAULT_LANGUAGE_FILE))
        world = _new_world(mode, 6, init_pop, seed_genome)

    placing = "food"
    cursor = [WIDTH / 2, HEIGHT / 2]

    paused = False
    speed = 1  # ticks per real second
    frame_time = 1 / 20
    tick_accumulator = 0.0

    while True:
        key = stdscr.getch()
        if key in (ord("q"), 27):
            break
        elif key == ord(" "):
            paused = not paused
        elif key == ord("r"):
            world = _new_world(mode, len(world.predators), init_pop, seed_genome)
        elif key in (ord("+"), ord("=")):
            speed = min(200, speed + (1 if speed < 10 else 10))
        elif key in (ord("-"), ord("_")):
            speed = max(1, speed - (1 if speed <= 10 else 10))
        elif key == ord("f") and mode == "auto":
            world.add_food(*world.rng.uniform([10, 10], [WIDTH - 10, HEIGHT - 10]))
        elif key == ord("p"):
            placing = "predator" if placing == "food" else "food"
        elif key == ord("["):
            world.remove_predator()
        elif key == ord("]"):
            world.add_random_predator()
        elif key == ord("s"):
            save_world(world, DEFAULT_SAVE_FILE)
            _flash_message(stdscr, lang, TEXT[lang]["save_confirmed"].format(file=DEFAULT_SAVE_FILE))
        elif key == ord("h"):
            show_help(stdscr, lang)
        elif key == curses.KEY_UP:
            cursor[1] = max(0.0, cursor[1] - CURSOR_STEP)
        elif key == curses.KEY_DOWN:
            cursor[1] = min(HEIGHT, cursor[1] + CURSOR_STEP)
        elif key == curses.KEY_LEFT:
            cursor[0] = max(0.0, cursor[0] - CURSOR_STEP)
        elif key == curses.KEY_RIGHT:
            cursor[0] = min(WIDTH, cursor[0] + CURSOR_STEP)
        elif key in ENTER_KEYS and mode == "manual":
            if placing == "food":
                world.add_food(cursor[0], cursor[1])
            else:
                world.add_predator(cursor[0], cursor[1])

        if not paused:
            tick_accumulator += frame_time
            tick_interval = 1.0 / speed
            while tick_accumulator >= tick_interval:
                world.step()
                tick_accumulator -= tick_interval
        else:
            tick_accumulator = 0.0

        draw(stdscr, world, paused, speed, mode, placing, cursor, lang, trained=seed_genome is not None)
        time.sleep(frame_time)


def main():
    parser = argparse.ArgumentParser(description="Thronglets - terminal renderer")
    parser.add_argument("--language", type=str, default=None,
                         help="seed the population with a train_language.py --export vocabulary "
                              "instead of starting from scratch")
    args = parser.parse_args()

    curses.wrapper(run, args.language)


if __name__ == "__main__":
    main()
