"""Watch a Thronglets world live in a window.

Runs fullscreen at the desktop's own resolution, stretching the world to
fill the screen exactly (each axis scaled independently, so no letterbox
bars regardless of aspect ratio). ESC quits back to the desktop.

You pick a language, automatic or manual mode, and whether to seed the AI
language once, at startup - not something you toggle mid-run.

Controls:
  SPACE        pause / resume
  UP / DOWN    simulation speed (ticks per real second - x1 is a genuine 1 tick/s)
  R            reset to a fresh world
  LEFT CLICK   place food (auto mode) or whatever's selected (manual mode)
  P            toggle what manual clicks place (food / predator)
  [ / ]        remove/add a predator right now
  H            in-game notice/help screen
  ESC          quit
"""

import argparse
import os
import random
import sys
import threading
import time

import pygame

from i18n import STATE_LABELS, TRAIT_LABELS
from simulation import (DANGER, DISTRESS, FOOD, Genome, HEIGHT, IDLE, MATE, MAX_POPULATION, N_TOKENS, N_TRAITS, World,
                         WIDTH, compare_seeds, load_seed_genome, load_world, save_world)

TRAIN_EPISODES = 3000
TRAIN_BATCH_SIZE = 256
TRAIN_LR = 0.01

DEFAULT_INIT_POP = 100
DEFAULT_LANGUAGE_FILE = "language_model.json"
DEFAULT_SAVE_FILE = "thronglets_save.json"

HUD_H = 244
# Placeholder sizes - main() overwrites these with the real screen resolution
# so the world fills the whole display with no letterboxing on either axis.
SCREEN_W, SCREEN_H = int(WIDTH * 5), int(HEIGHT * 5) + HUD_H
SCALE_X, SCALE_Y = 5.0, 5.0

BG = (18, 22, 16)
GROUND = (30, 38, 24)
HUD_BG = (10, 12, 9)
TEXT_COLOR = (220, 220, 210)
FOOD_COLOR = (110, 220, 90)
BODY_COLOR = (222, 208, 150)
PREDATOR_COLOR = (220, 30, 30)
TOKEN_COLORS = [
    (120, 120, 120),  # 0: silence, not drawn as a ring
    (235, 70, 70),
    (70, 140, 235),
    (245, 200, 60),
    (200, 90, 230),
    (70, 225, 210),
]

TEXT = {
    "en": {
        "choose_mode_prompt": "Choose the starting mode:",
        "choose_mode_auto": "  A = automatic - food and predators spawn on their own (default)",
        "choose_mode_manual": "  M = manual - you place everything yourself, nothing spawns alone",
        "choose_mode_hint": "Press A or M, or ENTER for the default (automatic).",

        "choose_pop_prompt": "How many creatures to start with? (1-{max}, default {default})",
        "choose_pop_hint": "Press ENTER to confirm.",

        "choose_traits_prompt": "Adaptive evolution: speed, vision, hearing, metabolism?",
        "choose_traits_explain1": "  Each creature gets its own physical stats, inherited and mutated -",
        "choose_traits_explain2": "  but faster/keener senses cost more energy, so it's a real trade-off.",
        "choose_traits_yes": "  Y = yes - physical traits evolve too, not just signaling",
        "choose_traits_no": "  N = no - everyone has the same fixed stats (default)",
        "choose_traits_hint": "Press Y or N, or ENTER for the default (no).",

        "choose_ai_prompt": "Activate the pre-trained AI language?",
        "choose_ai_subtitle": "  (reads '{file}', generated by train_language.py)",
        "choose_ai_yes": "  Y = yes - creatures already speak an unambiguous language (default)",
        "choose_ai_train": "  T = train a new one now, live, right here",
        "choose_ai_no": "  N = no - the language has to emerge on its own while you play",
        "choose_ai_hint": "Press Y, T, or N, or ENTER for the default (yes).",
        "ai_missing_file": "'{file}' not found - starting without AI.",
        "flash_hint": "-- press any key to continue --",

        "torch_missing": "PyTorch isn't installed - can't train here. Run 'pip install torch',\nor use a language_model.json trained elsewhere. Starting without AI.",
        "training_seed": "Training seed {seed} - this takes a little while, ESC cancels",
        "training_progress": "step {step}/{episodes}   loss {loss:.3f}   listener accuracy {acc:.0f}%",
        "training_elapsed": "{elapsed:.0f}s elapsed   {rate:.0f} steps/s",
        "training_explain": "Loss = how wrong the Listener's guesses still are (lower = better).",
        "training_explain2": "Accuracy = % of guesses it currently gets right, on this batch.",
        "training_live_title": "Current guess per state (still shifting - not final yet):",
        "training_result": "Seed {seed}: {outcome}   (overall accuracy {acc:.0f}%)",
        "training_clean": "no collisions - every state got its own color",
        "training_collision": "collision - two states share a color",
        "training_validate_hint": "V = use this seed   N = try another seed   ESC = cancel, no AI",
        "training_collision_hint": "This seed has a collision, can't be used as-is - N = try another seed   ESC = cancel, no AI",

        "choose_resume_prompt": "A saved game was found. Resume it?",
        "choose_resume_subtitle": "  (reads '{file}' - the population, food, and predators as you left them)",
        "choose_resume_yes": "  Y = yes - pick up exactly where you left off",
        "choose_resume_no": "  N = no - start a fresh game instead",
        "choose_resume_hint": "Press Y or N to continue.",
        "resume_load_failed": "'{file}' could not be read - starting a fresh game instead.",
        "save_confirmed": "Game saved to '{file}'.",

        "hud_paused": "PAUSED",
        "hud_trained_tag": "[trained vocabulary]",
        "hud_traits_tag": "[adaptive traits]",
        "hud_header": ("tick {tick:>6}   pop {pop:>4}   births {births:>5}   deaths {deaths:>5}   "
                        "{status}   (space=pause  up/down=speed  r=reset  s=save  g=graph  t=family  c=compare  "
                        "d=translator  f=faq  h=help)"),
        "hud_manual": "mode: manual   click places: {placing} (P)",
        "hud_auto": "mode: automatic   predators: {count} ([ / ] act immediately)",
        "placing_food": "food",
        "placing_predator": "predator",
        "hud_vocab_title": "vocabulary — every color in use per state, population share:",
        "graph_title": "Vocabulary over time - dominant share per state",
        "graph_traits_title": "Physical traits over time - population average (share of range)",
        "graph_dismiss": "-- press any key to go back --",
        "legend_creature": "creature (ring = its current signal)",
        "legend_food": "food",
        "legend_predator": "predator",
        "extinct": "Extinct. Press R to start a new world.",

        "translator_title": "Translator - what each color currently means",
        "translator_unused": "unused / ambiguous",
        "translator_homonym": "  ! homonym - shared with another state",

        "family_title": "Family tree",
        "family_gen": "generation {gen}",
        "family_alive": "alive - token {token}, age {age}",
        "family_dead": "dead since tick {death}",
        "family_born": "born at tick {tick}",
        "family_parents": "Parents:",
        "family_founder": "none - founding generation",
        "family_children": "Children ({n}):",
        "family_no_children": "none yet",
        "family_descendants": "Total descendants: {total} ({alive} still alive)",
        "family_hint": "UP=parent   DOWN=child   LEFT/RIGHT=siblings   T or ESC=go back",
        "family_none": "No creature to show yet.",

        "compare_mode_prompt": "Compare seeds: what should be reproducible?",
        "compare_mode_language": "  L = language - does the same word win across independent runs?",
        "compare_mode_traits": "  T = physical traits - do speed/vision/hearing/metabolism converge the same way?",
        "compare_mode_traits_unavailable": "  (traits unavailable - adaptive evolution is off for this world)",
        "compare_mode_hint": "Press L or T, or ESC to cancel.",
        "compare_depth_prompt": "How thorough?",
        "compare_depth_quick": "  R = quick - 4 seeds x 8,000 ticks (default)",
        "compare_depth_thorough": "  A = thorough - 8 seeds x 40,000 ticks, same as the manual check earlier",
        "compare_depth_expert": "  E = expert - 16 seeds x 60,000 ticks, runs one at a time - can take a while",
        "compare_depth_hint": "Press R, A, or E, or ENTER for the default (quick). ESC cancels.",
        "compare_progress": "seed {seed}/{n_seeds}   tick {tick}/{ticks}   ESC cancels",
        "compare_result_title": "Comparison done ({n_seeds} seeds x {ticks} ticks)",
        "compare_traits_header": "trait          mean   std dev    min     max",
        "compare_lang_header": "state          seeds' dominant color",
        "compare_collision_summary": "Collisions: {clean}/{n_seeds} seeds had none",
        "compare_dismiss": "-- ESC to go back --",
        "compare_cancelled": "Cancelled - {n} seed(s) completed before stopping.",

        "help_more": "-- space for more --",
        "help_dismiss": "-- press any key to resume --",
        "help_lines": [
            ("Thronglets - notice", True),
            ("", False),
            ("Each creature is born with a genome deciding which color it shows for", False),
            ("its current state, and how it reacts to colors it hears from others.", False),
            ("Nobody programs what a color means - a shared language can emerge", False),
            ("through natural selection, or it might not.", False),
            ("", False),
            ("The 5 states, in priority order:", True),
            ("  1. alarm-call    a predator was spotted -> flee immediately", False),
            ("  2. food-call     food is visible nearby", False),
            ("  3. distress-call energy critically low, no food in sight", False),
            ("  4. mate-call     ready to mate, and a ready partner is nearby", False),
            ("  5. idle          nothing special (by far the most common state)", False),
            ("", False),
            ("Living, mating, dying:", True),
            ("  Energy drains constantly; eating restores it. Emitting a color", False),
            ("  (other than silence) costs a bit of extra energy. Enough energy", False),
            ("  and age, plus a matching partner nearby: a child is born. A", False),
            ("  predator that catches a creature kills it outright.", False),
            ("", False),
            ("Reading the vocabulary rows at the top:", True),
            ("  For each state, the share of the population using each color.", False),
            ("  It starts near chance (~17%) and climbs if a token wins out.", False),
            ("  A '..' swatch means silence, not a missing color.", False),
            ("", False),
            ("Worth knowing:", True),
            ("  Two states can end up sharing the same color purely by chance", False),
            ("  (e.g. idle and alarm-call) - nothing prevents it or guarantees", False),
            ("  it resolves. Signaling costs energy, so silence is a real", False),
            ("  strategy, not a default.", False),
        ],
        "faq_lines": [
            ("Thronglets - FAQ", True),
            ("", False),
            ("Q: Why do creatures sometimes stay clustered even with food right", True),
            ("   next to them?", True),
            ("A: Following a neighbor's signal and heading for food are two", False),
            ("   forces that can partly cancel out - an accepted trade-off,", False),
            ("   not a bug.", False),
            ("", False),
            ("Q: Does distress make creatures help each other?", True),
            ("A: No - there's no cooperation mechanic. Distress is treated like", False),
            ("   any other signal, and creatures mostly learn to avoid it.", False),
            ("", False),
            ("Q: Why does the adaptive metabolism trait always drop to near its", True),
            ("   minimum?", True),
            ("A: Unlike speed/vision/hearing, a lower metabolism has zero", False),
            ("   downside here - it's not a real trade-off, so selection", False),
            ("   always pushes it down.", False),
            ("", False),
            ("Q: How can two creatures from very different generations be", True),
            ("   siblings?", True),
            ("A: Generation = max(both parents' generations)+1, and mate choice", False),
            ("   only cares about proximity, not generation - a long-lived", False),
            ("   parent can breed with a much 'deeper' partner late in life.", False),
            ("", False),
            ("Q: Can a creature really mate with its own descendant?", True),
            ("A: Yes - same reason: mate choice is purely proximity-based,", False),
            ("   with no notion of family.", False),
            ("", False),
            ("Q: Even a trained vocabulary can drift or 'flip back' - why?", True),
            ("A: No creature learns anything during its life; genomes are", False),
            ("   fixed at birth. Only mutation and selection across", False),
            ("   generations change anything, and mutation never stops -", False),
            ("   nothing is ever permanently locked in.", False),
            ("", False),
            ("Q: Two states share the same color (homonymy) - is that a bug?", True),
            ("A: No - nothing in the model prevents it. Genomes mutate per", False),
            ("   state independently, so two states can land on the same", False),
            ("   token by pure chance. Check the Translator screen (D) to", False),
            ("   see it clearly.", False),
            ("", False),
            ("Q: A single playthrough shows a surprising result - can I trust", True),
            ("   it?", True),
            ("A: Not on its own. Use the Compare screen (C) to run several", False),
            ("   independent seeds and see whether the result actually", False),
            ("   repeats, or was just one run's drift.", False),
            ("", False),
            ("Q: What's the real difference between the trained AI language", True),
            ("   and the evolved one?", True),
            ("A: The AI (train_language.py) uses gradient descent to directly", False),
            ("   minimize communication error, every step. The evolved", False),
            ("   language only rewards survival and reproduction - comm-", False),
            ("   unicating well is never optimized directly, just indirectly", False),
            ("   useful.", False),
        ],
    },
    "fr": {
        "choose_mode_prompt": "Choisis le mode de depart :",
        "choose_mode_auto": "  A = automatique - nourriture et predateurs apparaissent seuls (defaut)",
        "choose_mode_manual": "  M = manuel - tu places tout toi-meme, rien ne spawn seul",
        "choose_mode_hint": "Appuie sur A ou M, ou ENTREE pour le defaut (auto).",

        "choose_pop_prompt": "Combien de creatures au depart ? (1-{max}, defaut {default})",
        "choose_pop_hint": "Appuie sur ENTREE pour confirmer.",

        "choose_traits_prompt": "Evolution adaptative : vitesse, vision, ouie, metabolisme ?",
        "choose_traits_explain1": "  Chaque creature a ses propres stats physiques, heritees et mutees -",
        "choose_traits_explain2": "  mais etre rapide/perceptif coute plus d'energie, un vrai compromis.",
        "choose_traits_yes": "  O = oui - les traits physiques evoluent aussi, pas juste le langage",
        "choose_traits_no": "  N = non - tout le monde a les memes stats fixes (defaut)",
        "choose_traits_hint": "Appuie sur O ou N, ou ENTREE pour le defaut (non).",

        "choose_ai_prompt": "Activer le langage pre-entraine par IA ?",
        "choose_ai_subtitle": "  (relit '{file}', genere par train_language.py)",
        "choose_ai_yes": "  O = oui - les creatures parlent deja un langage sans confusion (defaut)",
        "choose_ai_train": "  T = en entrainer un nouveau maintenant, en direct, ici",
        "choose_ai_no": "  N = non - le langage doit emerger tout seul en jouant",
        "choose_ai_hint": "Appuie sur O, T ou N, ou ENTREE pour le defaut (oui).",
        "ai_missing_file": "'{file}' introuvable - lancement sans IA.",
        "flash_hint": "-- une touche pour continuer --",

        "torch_missing": "PyTorch n'est pas installe - entrainement impossible ici. Lance\n'pip install torch', ou utilise un language_model.json deja entraine ailleurs. Lancement sans IA.",
        "training_seed": "Entrainement de la seed {seed} - ca prend un moment, ESC annule",
        "training_progress": "etape {step}/{episodes}   perte {loss:.3f}   precision {acc:.0f}%",
        "training_elapsed": "{elapsed:.0f}s ecoulees   {rate:.0f} etapes/s",
        "training_explain": "Perte = a quel point le Listener se trompe encore (plus bas = mieux).",
        "training_explain2": "Precision = % de bonnes reponses actuellement, sur ce lot d'essais.",
        "training_live_title": "Devinette actuelle par etat (encore mouvante - pas definitive) :",
        "training_result": "Seed {seed} : {outcome}   (precision globale {acc:.0f}%)",
        "training_clean": "aucune collision - chaque etat a sa propre couleur",
        "training_collision": "collision - deux etats partagent une couleur",
        "training_validate_hint": "V = utiliser cette seed   N = essayer une autre   ESC = annuler, sans IA",
        "training_collision_hint": "Cette seed a une collision, inutilisable telle quelle - N = essayer une autre   ESC = annuler, sans IA",

        "choose_resume_prompt": "Une partie sauvegardee existe. La reprendre ?",
        "choose_resume_subtitle": "  (relit '{file}' - la population, la nourriture et les predateurs tels que laisses)",
        "choose_resume_yes": "  O = oui - reprendre exactement ou tu t'es arrete",
        "choose_resume_no": "  N = non - commencer une nouvelle partie",
        "choose_resume_hint": "Appuie sur O ou N pour continuer.",
        "resume_load_failed": "'{file}' illisible - nouvelle partie a la place.",
        "save_confirmed": "Partie sauvegardee dans '{file}'.",

        "hud_paused": "PAUSE",
        "hud_trained_tag": "[vocabulaire entraine]",
        "hud_traits_tag": "[traits evolutifs]",
        "hud_header": ("tick {tick:>6}   pop {pop:>4}   naissances {births:>5}   morts {deaths:>5}   "
                        "{status}   (espace=pause  haut/bas=vitesse  r=reset  s=sauver  g=graphique  t=famille  "
                        "c=comparer  d=traducteur  f=faq  h=aide)"),
        "hud_manual": "mode: manuel   clic pose : {placing} (P)",
        "hud_auto": "mode: auto   predateurs : {count} ([ / ] agit tout de suite)",
        "placing_food": "nourriture",
        "placing_predator": "predateur",
        "hud_vocab_title": "vocabulaire — toutes les couleurs en usage par etat, part de la population :",
        "graph_title": "Vocabulaire dans le temps - part dominante par etat",
        "graph_traits_title": "Traits physiques dans le temps - moyenne population (part de la plage)",
        "graph_dismiss": "-- une touche pour revenir --",
        "legend_creature": "creature (anneau = son signal actuel)",
        "legend_food": "nourriture",
        "legend_predator": "predateur",
        "extinct": "Extinction. Appuie sur R pour un nouveau monde.",

        "translator_title": "Traducteur - ce que signifie chaque couleur en ce moment",
        "translator_unused": "inutilisee / ambigue",
        "translator_homonym": "  ! homonymie - partagee avec un autre etat",

        "family_title": "Arbre genealogique",
        "family_gen": "generation {gen}",
        "family_alive": "vivant - token {token}, age {age}",
        "family_dead": "mort depuis le tick {death}",
        "family_born": "ne au tick {tick}",
        "family_parents": "Parents :",
        "family_founder": "aucun - generation fondatrice",
        "family_children": "Enfants ({n}) :",
        "family_no_children": "aucun pour le moment",
        "family_descendants": "Descendants au total : {total} ({alive} encore en vie)",
        "family_hint": "HAUT=parent   BAS=enfant   GAUCHE/DROITE=freres et soeurs   T ou ESC=revenir",
        "family_none": "Aucune creature a montrer pour le moment.",

        "compare_mode_prompt": "Comparer des seeds : qu'est-ce qui doit etre reproductible ?",
        "compare_mode_language": "  L = langage - le meme mot gagne-t-il sur des parties independantes ?",
        "compare_mode_traits": "  T = traits physiques - vitesse/vision/ouie/metabolisme convergent-ils pareil ?",
        "compare_mode_traits_unavailable": "  (traits indisponibles - evolution adaptative desactivee pour ce monde)",
        "compare_mode_hint": "Appuie sur L ou T, ou ESC pour annuler.",
        "compare_depth_prompt": "Quelle profondeur ?",
        "compare_depth_quick": "  R = rapide - 4 seeds x 8 000 ticks (defaut)",
        "compare_depth_thorough": "  A = approfondi - 8 seeds x 40 000 ticks, comme la verif faite plus tot",
        "compare_depth_expert": "  E = expert - 16 seeds x 60 000 ticks, une par une - peut prendre du temps",
        "compare_depth_hint": "Appuie sur R, A ou E, ou ENTREE pour le defaut (rapide). ESC annule.",
        "compare_progress": "seed {seed}/{n_seeds}   tick {tick}/{ticks}   ESC annule",
        "compare_result_title": "Comparaison terminee ({n_seeds} seeds x {ticks} ticks)",
        "compare_traits_header": "trait          moyenne  ecart-type  min     max",
        "compare_lang_header": "etat           couleur dominante par seed",
        "compare_collision_summary": "Collisions : {clean}/{n_seeds} seeds sans collision",
        "compare_dismiss": "-- ESC pour revenir --",
        "compare_cancelled": "Annule - {n} seed(s) terminee(s) avant l'arret.",

        "help_more": "-- espace pour la suite --",
        "help_dismiss": "-- une touche pour reprendre --",
        "help_lines": [
            ("Thronglets — notice", True),
            ("", False),
            ("Chaque creature nait avec un genome qui decide quelle couleur", False),
            ("elle affiche selon son etat, et comment elle reagit aux couleurs", False),
            ("des autres. Personne ne programme le sens des couleurs : un", False),
            ("langage commun peut emerger par selection naturelle, ou pas.", False),
            ("", False),
            ("Les 5 etats, par ordre de priorite :", True),
            ("  1. alerte     un predateur repere -> fuite immediate", False),
            ("  2. nourriture de la nourriture est visible tout pres", False),
            ("  3. detresse   energie tres basse, aucune nourriture en vue", False),
            ("  4. partenaire prete a se reproduire + partenaire prete proche", False),
            ("  5. inactif    rien de special (etat le plus frequent, de loin)", False),
            ("", False),
            ("Vivre, se reproduire, mourir :", True),
            ("  L'energie baisse en permanence, manger la restaure. Emettre", False),
            ("  une couleur (hors silence) coute un peu d'energie en plus.", False),
            ("  Assez d'energie et d'age, un partenaire pareil a proximite :", False),
            ("  un enfant nait. Un predateur qui attrape une creature la tue.", False),
            ("", False),
            ("Lire le vocabulaire affiche en haut :", True),
            ("  Pour chaque etat, la part de la population qui utilise chaque", False),
            ("  couleur. Ca part du hasard (~17%) et grimpe si un mot fait", False),
            ("  consensus. '..' = silence, pas une couleur en moins.", False),
            ("", False),
            ("A savoir :", True),
            ("  Deux etats peuvent finir sur la meme couleur par hasard (ex:", False),
            ("  inactif et alerte) - rien ne l'empeche ni ne garantit que ca", False),
            ("  se resolve. Parler coute de l'energie : le silence est une", False),
            ("  vraie strategie, pas un defaut.", False),
        ],
        "faq_lines": [
            ("Thronglets — FAQ", True),
            ("", False),
            ("Q : Pourquoi les creatures restent parfois en groupe meme avec", True),
            ("    de la nourriture juste a cote ?", True),
            ("R : Suivre le signal d'un voisin et se diriger vers la", False),
            ("    nourriture sont deux forces qui peuvent s'annuler en", False),
            ("    partie - un compromis assume, pas un bug.", False),
            ("", False),
            ("Q : Est-ce que la detresse pousse les creatures a s'entraider ?", True),
            ("R : Non - il n'y a aucun mecanisme de cooperation. La detresse", False),
            ("    est traitee comme n'importe quel autre signal, et les", False),
            ("    creatures apprennent surtout a l'eviter.", False),
            ("", False),
            ("Q : Pourquoi le metabolisme adaptatif tombe toujours pres de", True),
            ("    son minimum ?", True),
            ("R : Contrairement a la vitesse/vision/ouie, un metabolisme bas", False),
            ("    n'a aucun inconvenient ici - ce n'est pas un vrai", False),
            ("    compromis, donc la selection le pousse toujours vers le", False),
            ("    bas.", False),
            ("", False),
            ("Q : Comment deux creatures de generations tres differentes", True),
            ("    peuvent-elles etre frere et soeur ?", True),
            ("R : Generation = max(generation des deux parents)+1, et le", False),
            ("    choix du partenaire ne tient compte que de la proximite,", False),
            ("    pas de la generation - un parent qui vit longtemps peut se", False),
            ("    reproduire avec un partenaire bien plus 'profond' tard", False),
            ("    dans sa vie.", False),
            ("", False),
            ("Q : Une creature peut-elle vraiment s'accoupler avec son propre", True),
            ("    descendant ?", True),
            ("R : Oui - meme raison : le choix du partenaire est purement", False),
            ("    base sur la proximite, sans aucune notion de famille.", False),
            ("", False),
            ("Q : Meme un vocabulaire entraine peut deriver ou 'revenir en", True),
            ("    arriere' - pourquoi ?", True),
            ("R : Aucune creature n'apprend quoi que ce soit pendant sa vie ;", False),
            ("    les genomes sont fixes a la naissance. Seules la mutation", False),
            ("    et la selection a travers les generations changent quelque", False),
            ("    chose, et la mutation ne s'arrete jamais - rien n'est", False),
            ("    jamais definitivement acquis.", False),
            ("", False),
            ("Q : Deux etats partagent la meme couleur (homonymie) - c'est", True),
            ("    un bug ?", True),
            ("R : Non - rien dans le modele ne l'empeche. Les genomes mutent", False),
            ("    independamment par etat, donc deux etats peuvent tomber", False),
            ("    sur le meme token par pur hasard. L'ecran Traducteur (D)", False),
            ("    permet de le reperer clairement.", False),
            ("", False),
            ("Q : Une seule partie donne un resultat surprenant - puis-je lui", True),
            ("    faire confiance ?", True),
            ("R : Pas telle quelle. Utilise l'ecran Comparer (C) pour lancer", False),
            ("    plusieurs seeds independantes et voir si le resultat se", False),
            ("    reproduit vraiment, ou si c'etait juste la derive d'une", False),
            ("    seule partie.", False),
            ("", False),
            ("Q : Quelle est la vraie difference entre le langage entraine", True),
            ("    par IA et celui qui evolue ?", True),
            ("R : L'IA (train_language.py) utilise la descente de gradient", False),
            ("    pour minimiser directement l'erreur de communication, a", False),
            ("    chaque etape. Le langage evolue ne recompense que la", False),
            ("    survie et la reproduction - bien communiquer n'est jamais", False),
            ("    optimise directement, juste utile indirectement.", False),
        ],
    },
}


def show_help(screen, font, lang):
    t = TEXT[lang]
    lines = t["help_lines"]
    line_h = 24
    top = 20
    page_size = max(1, (SCREEN_H - top - 50) // line_h)
    for start in range(0, len(lines), page_size):
        page = lines[start:start + page_size]
        more = start + page_size < len(lines)
        footer = t["help_more"] if more else t["help_dismiss"]
        waiting = True
        while waiting:
            screen.fill(BG)
            for i, (line, bold) in enumerate(page):
                color = TEXT_COLOR if not bold else (255, 255, 255)
                screen.blit(font.render(line, True, color), (20, top + i * line_h))
            screen.blit(font.render(footer, True, (150, 155, 145)), (20, top + len(page) * line_h + 14))
            pygame.display.flip()
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    sys.exit()
                elif event.type == pygame.KEYDOWN:
                    waiting = False


def show_faq(screen, font, lang):
    """Paginated the same way as show_help() - curated questions that came
    up while building/playing this, with honest, specific answers."""
    t = TEXT[lang]
    lines = t["faq_lines"]
    line_h = 24
    top = 20
    page_size = max(1, (SCREEN_H - top - 50) // line_h)
    for start in range(0, len(lines), page_size):
        page = lines[start:start + page_size]
        more = start + page_size < len(lines)
        footer = t["help_more"] if more else t["help_dismiss"]
        waiting = True
        while waiting:
            screen.fill(BG)
            for i, (line, bold) in enumerate(page):
                color = TEXT_COLOR if not bold else (255, 255, 255)
                screen.blit(font.render(line, True, color), (20, top + i * line_h))
            screen.blit(font.render(footer, True, (150, 155, 145)), (20, top + len(page) * line_h + 14))
            pygame.display.flip()
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    sys.exit()
                elif event.type == pygame.KEYDOWN:
                    waiting = False


def show_graph(screen, font, world, lang):
    """A dedicated full-screen view of vocab_history (and trait_history, if
    adaptive traits are on), opened like show_help() - the HUD rows stay
    compact, this is where the curves get room to breathe."""
    t = TEXT[lang]
    labels = STATE_LABELS[lang]
    trait_labels = TRAIT_LABELS[lang]
    n_rows = 5 + (N_TRAITS if world.adaptive_traits else 0)
    title_h = 40 if world.adaptive_traits else 0
    row_h = (SCREEN_H - 80 - title_h) // n_rows
    graph_w = SCREEN_W - 260
    graph_h = min(60, row_h - 30)

    waiting = True
    while waiting:
        screen.fill(BG)
        screen.blit(font.render(t["graph_title"], True, (255, 255, 255)), (20, 20))

        y = 60
        for state in (DANGER, FOOD, DISTRESS, MATE, IDLE):
            history = world.vocab_history[state]
            current = f"{history[-1] * 100:3.0f}%" if history else "  -%"
            screen.blit(font.render(f"{labels[state]}: {current}", True, TEXT_COLOR), (20, y))
            draw_sparkline(screen, 220, y - 6, graph_w, graph_h, history)
            y += row_h

        if world.adaptive_traits:
            y += 10
            screen.blit(font.render(t["graph_traits_title"], True, (255, 255, 255)), (20, y))
            y += 30
            for trait in range(N_TRAITS):
                history = world.trait_history[trait]
                current = f"{history[-1] * 100:3.0f}%" if history else "  -%"
                screen.blit(font.render(f"{trait_labels[trait]}: {current}", True, TEXT_COLOR), (20, y))
                draw_sparkline(screen, 220, y - 6, graph_w, graph_h, history)
                y += row_h

        screen.blit(font.render(t["graph_dismiss"], True, (150, 155, 145)), (20, y))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                waiting = False


def show_translator(screen, font, world, lang):
    """A frozen snapshot - what each color means right now, inverted from
    the HUD's state->color view into a color->state dictionary. Opened like
    show_graph()/show_help(); no history, just this instant."""
    t = TEXT[lang]
    labels = STATE_LABELS[lang]
    by_token = world.translator()

    waiting = True
    while waiting:
        screen.fill(BG)
        screen.blit(font.render(t["translator_title"], True, (255, 255, 255)), (20, 20))

        y = 60
        for token in range(N_TOKENS):
            claims = by_token[token]
            if token == 0:
                pygame.draw.circle(screen, (110, 110, 110), (30, y + 8), 6, width=1)
            else:
                pygame.draw.circle(screen, TOKEN_COLORS[token], (30, y + 8), 6)
            text = (" / ".join(f"{labels[state]} ({frac * 100:.0f}%)" for state, frac in claims)
                    if claims else t["translator_unused"])
            screen.blit(font.render(text, True, TEXT_COLOR), (46, y))
            y += 24
            if len(claims) > 1:
                screen.blit(font.render(t["translator_homonym"], True, (235, 90, 90)), (46, y))
                y += 24

        screen.blit(font.render(t["graph_dismiss"], True, (150, 155, 145)), (20, y + 16))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                waiting = False


def _family_short_label(world, cid):
    rec = world.lineage.get(cid)
    if rec is None:
        return f"#{cid}"
    if rec["death"] is None:
        return f"#{cid} (gen {rec['gen']}, alive)"
    return f"#{cid} (gen {rec['gen']}, dead t{rec['death']})"


def show_family(screen, font, world, lang):
    """An ego-centric genealogy browser, opened like show_graph()/show_help():
    one creature in focus at a time, arrow keys walk the tree (parent above,
    first child below, siblings sideways) instead of trying to cram a whole
    population's tree onto one screen."""
    t = TEXT[lang]
    focus = world.default_family_focus()
    if focus is None:
        waiting = True
        while waiting:
            screen.fill(BG)
            screen.blit(font.render(t["family_none"], True, (255, 255, 255)), (20, 20))
            screen.blit(font.render(t["graph_dismiss"], True, (150, 155, 145)), (20, 60))
            pygame.display.flip()
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    sys.exit()
                elif event.type == pygame.KEYDOWN:
                    waiting = False
        return

    line_h = 26
    while True:
        info = world.family_info(focus)
        screen.fill(BG)
        y = 20
        screen.blit(font.render(t["family_title"], True, (255, 255, 255)), (20, y))
        y += line_h * 2

        screen.blit(font.render(f"#{info['id']}  {t['family_gen'].format(gen=info['gen'])}",
                                 True, (255, 255, 255)), (20, y))
        y += line_h
        status = (t["family_alive"].format(token=info["token"], age=info["age"]) if info["alive"]
                  else t["family_dead"].format(death=info["death"]))
        color = TOKEN_COLORS[info["token"]] if info["alive"] and info["token"] else TEXT_COLOR
        screen.blit(font.render(status, True, color), (20, y))
        y += line_h
        screen.blit(font.render(t["family_born"].format(tick=info["birth"]), True, (150, 155, 145)), (20, y))
        y += line_h * 2

        screen.blit(font.render(t["family_parents"], True, (255, 255, 255)), (20, y))
        y += line_h
        if info["parents"]:
            for pid in info["parents"]:
                screen.blit(font.render(_family_short_label(world, pid), True, TEXT_COLOR), (40, y))
                y += line_h
        else:
            screen.blit(font.render(t["family_founder"], True, (150, 155, 145)), (40, y))
            y += line_h
        y += line_h // 2

        screen.blit(font.render(t["family_children"].format(n=len(info["children"])),
                                 True, (255, 255, 255)), (20, y))
        y += line_h
        if info["children"]:
            for cid in info["children"][:8]:
                screen.blit(font.render(_family_short_label(world, cid), True, TEXT_COLOR), (40, y))
                y += line_h
            if len(info["children"]) > 8:
                screen.blit(font.render(f"... +{len(info['children']) - 8}", True, (150, 155, 145)), (40, y))
                y += line_h
        else:
            screen.blit(font.render(t["family_no_children"], True, (150, 155, 145)), (40, y))
            y += line_h
        y += line_h // 2

        descendants = t["family_descendants"].format(total=info["total_descendants"], alive=info["alive_descendants"])
        screen.blit(font.render(descendants, True, TEXT_COLOR), (20, y))
        y += line_h * 2
        screen.blit(font.render(t["family_hint"], True, (150, 155, 145)), (20, y))
        pygame.display.flip()

        event_key = None
        waiting = True
        while waiting:
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    sys.exit()
                elif event.type == pygame.KEYDOWN:
                    event_key = event.key
                    waiting = False

        if event_key in (pygame.K_ESCAPE, pygame.K_t):
            break
        elif event_key == pygame.K_UP and info["parents"]:
            focus = info["parents"][0]
        elif event_key == pygame.K_DOWN and info["children"]:
            focus = info["children"][0]
        elif event_key in (pygame.K_LEFT, pygame.K_RIGHT) and info["parents"]:
            siblings = world.family_info(info["parents"][0])["children"]
            if focus in siblings and len(siblings) > 1:
                i = siblings.index(focus)
                i = (i + (1 if event_key == pygame.K_RIGHT else -1)) % len(siblings)
                focus = siblings[i]


def draw(screen, font, world, paused, speed, mode, placing, lang, trained=False):
    screen.fill(BG)
    pygame.draw.rect(screen, GROUND, (0, HUD_H, SCREEN_W, SCREEN_H - HUD_H))

    for fx, fy in world.food:
        pygame.draw.circle(screen, FOOD_COLOR, (int(fx * SCALE_X), int(fy * SCALE_Y) + HUD_H), 3)

    for c in world.creatures:
        if not c.alive:
            continue
        x, y = int(c.pos[0] * SCALE_X), int(c.pos[1] * SCALE_Y) + HUD_H
        pygame.draw.circle(screen, BODY_COLOR, (x, y), 4)
        if c.token != 0:
            pygame.draw.circle(screen, TOKEN_COLORS[c.token], (x, y), 7, width=2)

    for p in world.predators:
        x, y = int(p.pos[0] * SCALE_X), int(p.pos[1] * SCALE_Y) + HUD_H
        pygame.draw.circle(screen, PREDATOR_COLOR, (x, y), 6)

    draw_hud(screen, font, world, paused, speed, mode, placing, lang, trained)


SPARK_COLOR = (150, 200, 130)
SPARK_BG = (26, 32, 20)


def _downsample(values, max_points):
    """Bucket-average down to at most max_points - plotting one line segment
    per raw sample looks like a smooth curve for a short history, but once a
    run has thousands of samples squeezed into a few hundred pixels, the
    unavoidably tiny gaps between adjacent (noisy) points render as a dense
    picket-fence of near-vertical spikes instead of a readable trend."""
    if len(values) <= max_points:
        return values
    bucket = len(values) / max_points
    return [
        sum(values[lo:hi]) / (hi - lo)
        for lo, hi in (
            (int(i * bucket), max(int(i * bucket) + 1, int((i + 1) * bucket)))
            for i in range(max_points)
        )
    ]


def draw_sparkline(screen, x, y, w, h, history):
    rect = pygame.Rect(x, y, w, h)
    pygame.draw.rect(screen, SPARK_BG, rect)
    if len(history) < 2:
        return
    values = _downsample(list(history), max(2, int(w)))
    step = w / (len(values) - 1)
    points = [
        (x + i * step, y + h - 1 - v * (h - 2))
        for i, v in enumerate(values)
    ]
    pygame.draw.lines(screen, SPARK_COLOR, False, points, width=2)


def draw_vocab_row(screen, font, y, label, pairs):
    x = 10
    lbl = font.render(f"{label}:", True, TEXT_COLOR)
    screen.blit(lbl, (x, y))
    x += lbl.get_width() + 10
    for token, frac in pairs:
        if token == 0:
            pygame.draw.circle(screen, (110, 110, 110), (x + 6, y + 8), 6, width=1)
        else:
            pygame.draw.circle(screen, TOKEN_COLORS[token], (x + 6, y + 8), 6)
        txt = font.render(f"{frac * 100:3.0f}%", True, TEXT_COLOR)
        screen.blit(txt, (x + 16, y))
        x += 16 + txt.get_width() + 14


def draw_hud(screen, font, world, paused, speed, mode, placing, lang, trained=False):
    t = TEXT[lang]
    labels = STATE_LABELS[lang]
    pygame.draw.rect(screen, HUD_BG, (0, 0, SCREEN_W, HUD_H))
    pop = world.population()
    status = t["hud_paused"] if paused else f"x{speed}"
    tag_parts = [t["hud_trained_tag"]] if trained else []
    if world.adaptive_traits:
        tag_parts.append(t["hud_traits_tag"])
    tag = "   ".join(tag_parts)
    header = t["hud_header"].format(tick=world.tick, pop=pop, births=world.births,
                                     deaths=world.deaths, status=status)
    screen.blit(font.render(header, True, TEXT_COLOR), (10, 8))
    if tag:
        screen.blit(font.render(tag, True, TEXT_COLOR), (10, 28))

    if mode == "manual":
        placing_label = t["placing_food"] if placing == "food" else t["placing_predator"]
        settings = t["hud_manual"].format(placing=placing_label)
    else:
        settings = t["hud_auto"].format(count=len(world.predators))
    screen.blit(font.render(settings, True, TEXT_COLOR), (10, 48))

    screen.blit(font.render(t["hud_vocab_title"], True, TEXT_COLOR), (10, 68))

    y = 90
    breakdown = world.vocabulary_breakdown()
    for state in (DANGER, FOOD, DISTRESS, MATE, IDLE):
        draw_vocab_row(screen, font, y, labels[state], breakdown[state])
        y += 22

    legend_y = y
    lx = 10
    pygame.draw.circle(screen, BODY_COLOR, (lx + 6, legend_y + 8), 4)
    pygame.draw.circle(screen, (150, 150, 150), (lx + 6, legend_y + 8), 7, width=2)
    txt = font.render(t["legend_creature"], True, TEXT_COLOR)
    screen.blit(txt, (lx + 18, legend_y))
    lx += 18 + txt.get_width() + 20

    pygame.draw.circle(screen, FOOD_COLOR, (lx + 6, legend_y + 8), 3)
    txt = font.render(t["legend_food"], True, TEXT_COLOR)
    screen.blit(txt, (lx + 18, legend_y))
    lx += 18 + txt.get_width() + 20

    pygame.draw.circle(screen, PREDATOR_COLOR, (lx + 6, legend_y + 8), 6)
    txt = font.render(t["legend_predator"], True, TEXT_COLOR)
    screen.blit(txt, (lx + 18, legend_y))

    if pop == 0:
        msg = font.render(t["extinct"], True, (235, 90, 90))
        screen.blit(msg, (10, legend_y + 22))


def _new_world(mode, predator_count, init_pop=DEFAULT_INIT_POP, seed_genome=None, adaptive_traits=False):
    if mode == "manual":
        return World(init_pop=init_pop, manual_food=True, manual_predators=True,
                      seed_genome=seed_genome, adaptive_traits=adaptive_traits)
    return World(init_pop=init_pop, predator_count=predator_count,
                 seed_genome=seed_genome, adaptive_traits=adaptive_traits)


def choose_language(screen, font):
    lines = [
        "Thronglets",
        "",
        "Choose your language / Choisis ta langue :",
        "  E = English",
        "  F = Francais (defaut)",
        "",
        "Press E or F to continue, or ENTER for the default (Francais).",
    ]
    while True:
        screen.fill(BG)
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_e:
                    return "en"
                if event.key == pygame.K_f or event.key == pygame.K_RETURN:
                    return "fr"


def choose_mode(screen, font, lang):
    t = TEXT[lang]
    lines = [
        "Thronglets",
        "",
        t["choose_mode_prompt"],
        t["choose_mode_auto"],
        t["choose_mode_manual"],
        "",
        t["choose_mode_hint"],
    ]
    while True:
        screen.fill(BG)
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_a or event.key == pygame.K_RETURN:
                    return "auto"
                if event.key == pygame.K_m:
                    return "manual"


def choose_population(screen, font, lang):
    t = TEXT[lang]
    text = ""
    while True:
        screen.fill(BG)
        lines = [
            "Thronglets",
            "",
            t["choose_pop_prompt"].format(max=MAX_POPULATION, default=DEFAULT_INIT_POP),
            "",
            f"> {text}",
            "",
            t["choose_pop_hint"],
        ]
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_RETURN:
                    if not text:
                        return DEFAULT_INIT_POP
                    return max(1, min(MAX_POPULATION, int(text)))
                elif event.key == pygame.K_BACKSPACE:
                    text = text[:-1]
                elif event.unicode.isdigit() and len(text) < 3:
                    text += event.unicode


def choose_adaptive_traits(screen, font, lang):
    t = TEXT[lang]
    lines = [
        "Thronglets",
        "",
        t["choose_traits_prompt"],
        t["choose_traits_explain1"],
        t["choose_traits_explain2"],
        "",
        t["choose_traits_yes"],
        t["choose_traits_no"],
        "",
        t["choose_traits_hint"],
    ]
    yes_key = pygame.K_o if lang == "fr" else pygame.K_y
    while True:
        screen.fill(BG)
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == yes_key:
                    return True
                if event.key == pygame.K_n or event.key == pygame.K_RETURN:
                    return False


def choose_ai(screen, font, lang):
    t = TEXT[lang]
    lines = [
        "Thronglets",
        "",
        t["choose_ai_prompt"],
        t["choose_ai_subtitle"].format(file=DEFAULT_LANGUAGE_FILE),
        "",
        t["choose_ai_yes"],
        t["choose_ai_train"],
        t["choose_ai_no"],
        "",
        t["choose_ai_hint"],
    ]
    yes_key = pygame.K_o if lang == "fr" else pygame.K_y
    while True:
        screen.fill(BG)
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == yes_key or event.key == pygame.K_RETURN:
                    return "yes"
                if event.key == pygame.K_t:
                    return "train"
                if event.key == pygame.K_n:
                    return "no"


def choose_resume(screen, font, lang):
    t = TEXT[lang]
    lines = [
        "Thronglets",
        "",
        t["choose_resume_prompt"],
        t["choose_resume_subtitle"].format(file=DEFAULT_SAVE_FILE),
        "",
        t["choose_resume_yes"],
        t["choose_resume_no"],
        "",
        t["choose_resume_hint"],
    ]
    yes_key = pygame.K_o if lang == "fr" else pygame.K_y
    while True:
        screen.fill(BG)
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == yes_key:
                    return True
                if event.key == pygame.K_n:
                    return False


def flash_message(screen, font, lang, text):
    lines = text.split("\n")
    waiting = True
    while waiting:
        screen.fill(BG)
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, (235, 90, 90)), (20, 20 + i * 24))
        screen.blit(font.render(TEXT[lang]["flash_hint"], True, TEXT_COLOR), (20, 20 + len(lines) * 24 + 20))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                waiting = False


def _import_train_language():
    """Lazy on purpose: only the "train a new one now" path needs PyTorch,
    so the rest of main.py stays usable without it installed."""
    try:
        import train_language
        return train_language
    except ImportError:
        return None


def run_training_ui(screen, font, lang):
    """In-app equivalent of `train_language.py --sweep`, but interactive:
    trains one seed at a time, shows live progress, and lets you accept a
    seed the moment you're happy with it instead of committing to a fixed
    seed count up front. Returns a ready-to-use Genome, or None if PyTorch
    isn't available or the user cancels."""
    t = TEXT[lang]
    train_language = _import_train_language()
    if train_language is None:
        flash_message(screen, font, lang, t["torch_missing"])
        return None

    labels = STATE_LABELS[lang]
    validate_key = pygame.K_v
    clock = pygame.time.Clock()
    tried_seeds = set()

    def next_seed():
        while True:
            s = random.randint(0, 999_999)
            if s not in tried_seeds:
                tried_seeds.add(s)
                return s

    seed = next_seed()

    while True:
        cancel_event = threading.Event()
        progress = {"step": 0, "episodes": TRAIN_EPISODES, "loss": 0.0, "acc": 0.0, "state_to_token": None}
        progress_lock = threading.Lock()
        result = {}

        def on_progress(step, episodes, loss, acc, temperature, state_to_token):
            with progress_lock:
                progress.update(step=step, episodes=episodes, loss=loss, acc=acc, state_to_token=state_to_token)

        def worker():
            speaker, listener = train_language.train(
                TRAIN_EPISODES, TRAIN_BATCH_SIZE, True, TRAIN_LR, seed,
                verbose=False, progress_callback=on_progress, cancel_event=cancel_event,
            )
            result["speaker"] = speaker
            result["listener"] = listener

        start_time = time.monotonic()
        thread = threading.Thread(target=worker, daemon=True)
        thread.start()

        cancelled = False
        while thread.is_alive():
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    sys.exit()
                elif event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                    cancel_event.set()
                    cancelled = True

            with progress_lock:
                step, episodes = progress["step"], progress["episodes"]
                loss, acc = progress["loss"], progress["acc"]
                state_to_token = progress["state_to_token"]
            elapsed = time.monotonic() - start_time
            rate = step / elapsed if elapsed > 0 else 0.0

            screen.fill(BG)
            lines = [
                "Thronglets",
                "",
                t["training_seed"].format(seed=seed),
                t["training_progress"].format(step=step, episodes=episodes, loss=loss, acc=acc * 100),
                t["training_elapsed"].format(elapsed=elapsed, rate=rate),
            ]
            for i, line in enumerate(lines):
                screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
            y = 20 + len(lines) * 26

            bar_x, bar_w, bar_h = 20, 400, 14
            frac = step / episodes if episodes else 0.0
            pygame.draw.rect(screen, (60, 66, 54), (bar_x, y, bar_w, bar_h))
            pygame.draw.rect(screen, (110, 220, 90), (bar_x, y, int(bar_w * frac), bar_h))
            y += bar_h + 20

            screen.blit(font.render(t["training_explain"], True, (150, 155, 145)), (20, y))
            y += 22
            screen.blit(font.render(t["training_explain2"], True, (150, 155, 145)), (20, y))
            y += 34

            screen.blit(font.render(t["training_live_title"], True, TEXT_COLOR), (20, y))
            y += 26
            if state_to_token is not None:
                for state in (DANGER, FOOD, DISTRESS, MATE, IDLE):
                    token = state_to_token[state]
                    lbl = font.render(f"  {labels[state]:<14}", True, TEXT_COLOR)
                    screen.blit(lbl, (20, y))
                    cx = 20 + lbl.get_width() + 16
                    if token == 0:
                        pygame.draw.circle(screen, (110, 110, 110), (cx, y + 8), 6, width=1)
                    else:
                        pygame.draw.circle(screen, TOKEN_COLORS[token], (cx, y + 8), 6)
                    y += 24

            pygame.display.flip()
            clock.tick(30)

        thread.join()
        if cancelled:
            return None

        speaker, listener = result["speaker"], result["listener"]
        _, collision, acc = train_language.evaluate(speaker, listener)
        state_to_token, token_to_state = train_language.compute_lookup(speaker, listener)

        outcome = t["training_collision"] if collision else t["training_clean"]
        header_lines = [
            "Thronglets",
            "",
            t["training_result"].format(seed=seed, outcome=outcome, acc=acc * 100),
        ]
        footer_line = t["training_collision_hint"] if collision else t["training_validate_hint"]

        choice = None
        while choice is None:
            screen.fill(BG)
            for i, line in enumerate(header_lines):
                screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
            y = 20 + len(header_lines) * 26 + 20
            for state in (DANGER, FOOD, DISTRESS, MATE, IDLE):
                token = state_to_token[state]
                lbl = font.render(f"  {labels[state]:<14}", True, TEXT_COLOR)
                screen.blit(lbl, (20, y))
                cx = 20 + lbl.get_width() + 16
                if token == 0:
                    pygame.draw.circle(screen, (110, 110, 110), (cx, y + 8), 6, width=1)
                else:
                    pygame.draw.circle(screen, TOKEN_COLORS[token], (cx, y + 8), 6)
                y += 24
            screen.blit(font.render(footer_line, True, TEXT_COLOR), (20, y + 20))
            pygame.display.flip()
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    sys.exit()
                elif event.type == pygame.KEYDOWN:
                    if event.key == validate_key and not collision:
                        choice = "accept"
                    elif event.key == pygame.K_n:
                        choice = "next"
                    elif event.key == pygame.K_ESCAPE:
                        choice = "cancel"
            clock.tick(30)

        if choice == "accept":
            train_language.export_vocabulary(speaker, listener, DEFAULT_LANGUAGE_FILE)
            return Genome.from_lookup(state_to_token, token_to_state)
        if choice == "cancel":
            return None
        seed = next_seed()


COMPARE_QUICK = (4, 8000)
COMPARE_THOROUGH = (8, 40000)
COMPARE_EXPERT = (16, 60000)


def choose_compare_mode(screen, font, lang, traits_available):
    t = TEXT[lang]
    lines = [
        "Thronglets",
        "",
        t["compare_mode_prompt"],
        t["compare_mode_language"],
        t["compare_mode_traits"] if traits_available else t["compare_mode_traits_unavailable"],
        "",
        t["compare_mode_hint"],
    ]
    while True:
        screen.fill(BG)
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_l:
                    return "language"
                if event.key == pygame.K_t and traits_available:
                    return "traits"
                if event.key == pygame.K_ESCAPE:
                    return None


def choose_compare_depth(screen, font, lang):
    t = TEXT[lang]
    lines = [
        "Thronglets",
        "",
        t["compare_depth_prompt"],
        t["compare_depth_quick"],
        t["compare_depth_thorough"],
        t["compare_depth_expert"],
        "",
        t["compare_depth_hint"],
    ]
    while True:
        screen.fill(BG)
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_r or event.key == pygame.K_RETURN:
                    return COMPARE_QUICK
                if event.key == pygame.K_a:
                    return COMPARE_THOROUGH
                if event.key == pygame.K_e:
                    return COMPARE_EXPERT
                if event.key == pygame.K_ESCAPE:
                    return None


def run_compare_ui(screen, font, world, lang, init_pop, seed_genome):
    """Runs simulation.compare_seeds() in a background thread with a live
    progress screen (same shape as run_training_ui's), then shows a results
    table. Purely a side experiment - never touches the live `world`."""
    t = TEXT[lang]
    labels = STATE_LABELS[lang]
    trait_labels = TRAIT_LABELS[lang]

    mode = choose_compare_mode(screen, font, lang, world.adaptive_traits)
    if mode is None:
        return
    depth = choose_compare_depth(screen, font, lang)
    if depth is None:
        return
    n_seeds, ticks = depth

    clock = pygame.time.Clock()
    cancel_event = threading.Event()
    progress = {"seed": 0, "tick": 0}
    progress_lock = threading.Lock()
    result = {}

    def on_progress(seed_i, n, tick, total_ticks):
        with progress_lock:
            progress.update(seed=seed_i + 1, tick=tick)

    def worker():
        result["results"] = compare_seeds(
            n_seeds, ticks, init_pop, len(world.predators), mode == "traits",
            seed_genome=seed_genome, progress_callback=on_progress, cancel_event=cancel_event,
        )

    thread = threading.Thread(target=worker, daemon=True)
    thread.start()

    cancelled = False
    while thread.is_alive():
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                cancel_event.set()
                cancelled = True

        with progress_lock:
            seed_n, tick = progress["seed"], progress["tick"]
        screen.fill(BG)
        lines = [
            "Thronglets",
            "",
            t["compare_progress"].format(seed=max(1, seed_n), n_seeds=n_seeds, tick=tick, ticks=ticks),
        ]
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        clock.tick(30)

    thread.join()
    results = result.get("results", [])
    if cancelled and not results:
        flash_message(screen, font, lang, t["compare_cancelled"].format(n=len(results)))
        return

    waiting = True
    while waiting:
        screen.fill(BG)
        y = 20
        screen.blit(font.render(t["compare_result_title"].format(n_seeds=len(results), ticks=ticks),
                                 True, (255, 255, 255)), (20, y))
        y += 40

        if mode == "traits":
            screen.blit(font.render(t["compare_traits_header"], True, TEXT_COLOR), (20, y))
            y += 26
            for trait in range(N_TRAITS):
                vals = [r["traits"][trait] * 100 for r in results if r["traits"] is not None]
                mean = sum(vals) / len(vals)
                std = (sum((v - mean) ** 2 for v in vals) / len(vals)) ** 0.5
                row = f"{trait_labels[trait]:<14} {mean:5.1f}%   {std:5.1f}%   {min(vals):5.1f}%  {max(vals):5.1f}%"
                screen.blit(font.render(row, True, TEXT_COLOR), (20, y))
                y += 24
        else:
            screen.blit(font.render(t["compare_lang_header"], True, TEXT_COLOR), (20, y))
            y += 26
            for state in (DANGER, FOOD, DISTRESS, MATE, IDLE):
                lbl = font.render(f"  {labels[state]:<14}", True, TEXT_COLOR)
                screen.blit(lbl, (20, y))
                cx = 20 + lbl.get_width() + 10
                for r in results:
                    token = r["vocab"][state][0]
                    if token == 0:
                        pygame.draw.circle(screen, (110, 110, 110), (cx, y + 8), 6, width=1)
                    else:
                        pygame.draw.circle(screen, TOKEN_COLORS[token], (cx, y + 8), 6)
                    cx += 20
                y += 24
            y += 10
            clean = sum(1 for r in results if not r["collision"])
            screen.blit(font.render(t["compare_collision_summary"].format(clean=clean, n_seeds=len(results)),
                                     True, TEXT_COLOR), (20, y))
            y += 26

        if cancelled:
            y += 10
            screen.blit(font.render(t["compare_cancelled"].format(n=len(results)), True, (235, 90, 90)), (20, y))
            y += 26

        screen.blit(font.render(t["compare_dismiss"], True, (150, 155, 145)), (20, y + 14))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
                waiting = False


def main():
    parser = argparse.ArgumentParser(description="Thronglets - pygame renderer")
    parser.add_argument("--language", type=str, default=None,
                         help="seed the population with a train_language.py --export vocabulary "
                              "instead of starting from scratch")
    args = parser.parse_args()

    pygame.init()
    pygame.display.set_caption("Thronglets - a tiny language is being born")
    # (0, 0) + FULLSCREEN asks SDL for the desktop's own resolution, then the
    # world is stretched per-axis to exactly fill it - no fixed aspect ratio,
    # so no letterboxing bars on wide/narrow screens.
    screen = pygame.display.set_mode((0, 0), pygame.FULLSCREEN)
    global SCREEN_W, SCREEN_H, SCALE_X, SCALE_Y
    SCREEN_W, SCREEN_H = screen.get_size()
    SCALE_X = SCREEN_W / WIDTH
    SCALE_Y = (SCREEN_H - HUD_H) / HEIGHT
    clock = pygame.time.Clock()
    font = pygame.font.SysFont("consolas", 16)

    lang = choose_language(screen, font)

    world = None
    if os.path.exists(DEFAULT_SAVE_FILE) and choose_resume(screen, font, lang):
        try:
            world = load_world(DEFAULT_SAVE_FILE)
            mode = "manual" if (world.manual_food or world.manual_predators) else "auto"
            init_pop = world.population()
        except (OSError, ValueError, KeyError):
            world = None
            flash_message(screen, font, lang, TEXT[lang]["resume_load_failed"].format(file=DEFAULT_SAVE_FILE))

    seed_genome = None
    if world is None:
        mode = choose_mode(screen, font, lang)
        init_pop = choose_population(screen, font, lang)
        adaptive_traits = choose_adaptive_traits(screen, font, lang)

        if args.language:
            seed_genome = load_seed_genome(args.language)
        else:
            ai_choice = choose_ai(screen, font, lang)
            if ai_choice == "yes":
                try:
                    seed_genome = load_seed_genome(DEFAULT_LANGUAGE_FILE)
                except OSError:
                    seed_genome = None
                    flash_message(screen, font, lang,
                                  TEXT[lang]["ai_missing_file"].format(file=DEFAULT_LANGUAGE_FILE))
            elif ai_choice == "train":
                seed_genome = run_training_ui(screen, font, lang)
        world = _new_world(mode, 6, init_pop, seed_genome, adaptive_traits)
    else:
        adaptive_traits = world.adaptive_traits

    placing = "food"
    paused = False
    speed = 1  # ticks per real second
    tick_accumulator = 0.0
    running = True

    while running:
        # Capped so returning from a blocking screen (help, save confirmation)
        # resumes at normal pace instead of fast-forwarding through a huge backlog.
        dt = min(clock.tick(60) / 1000.0, 0.25)
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                elif event.key == pygame.K_SPACE:
                    paused = not paused
                elif event.key == pygame.K_r:
                    world = _new_world(mode, len(world.predators), init_pop, seed_genome, adaptive_traits)
                elif event.key == pygame.K_UP:
                    speed = min(200, speed + (1 if speed < 10 else 10))
                elif event.key == pygame.K_DOWN:
                    speed = max(1, speed - (1 if speed <= 10 else 10))
                elif event.key == pygame.K_p:
                    placing = "predator" if placing == "food" else "food"
                elif event.key == pygame.K_LEFTBRACKET:
                    world.remove_predator()
                elif event.key == pygame.K_RIGHTBRACKET:
                    world.add_random_predator()
                elif event.key == pygame.K_s:
                    save_world(world, DEFAULT_SAVE_FILE)
                    flash_message(screen, font, lang, TEXT[lang]["save_confirmed"].format(file=DEFAULT_SAVE_FILE))
                elif event.key == pygame.K_g:
                    show_graph(screen, font, world, lang)
                elif event.key == pygame.K_t:
                    show_family(screen, font, world, lang)
                elif event.key == pygame.K_c:
                    run_compare_ui(screen, font, world, lang, init_pop, seed_genome)
                elif event.key == pygame.K_d:
                    show_translator(screen, font, world, lang)
                elif event.key == pygame.K_f:
                    show_faq(screen, font, lang)
                elif event.key == pygame.K_h:
                    show_help(screen, font, lang)
            elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
                mx, my = event.pos
                if my > HUD_H:
                    wx, wy = mx / SCALE_X, (my - HUD_H) / SCALE_Y
                    if mode == "manual" and placing == "predator":
                        world.add_predator(wx, wy)
                    else:
                        world.add_food(wx, wy)

        if not paused:
            tick_accumulator += dt
            tick_interval = 1.0 / speed
            while tick_accumulator >= tick_interval:
                world.step()
                tick_accumulator -= tick_interval
        else:
            tick_accumulator = 0.0

        draw(screen, font, world, paused, speed, mode, placing, lang, trained=seed_genome is not None)
        pygame.display.flip()

    pygame.quit()
    sys.exit()


if __name__ == "__main__":
    main()
