"""Watch a Thronglets world live in a window.

Runs fullscreen, scaled to fit whatever resolution the screen actually is
(pygame's SCALED flag letterboxes rather than stretching), so it never
shows up bigger than the display. ESC quits back to the desktop.

You pick a language, automatic or manual mode, and whether to seed the AI
language once, at startup - not something you toggle mid-run.

Controls:
  SPACE        pause / resume
  UP / DOWN    simulation speed (ticks per rendered frame)
  R            reset to a fresh world
  LEFT CLICK   place food (auto mode) or whatever's selected (manual mode)
  P            toggle what manual clicks place (food / predator)
  [ / ]        remove/add a predator right now
  H            in-game notice/help screen
  ESC          quit
"""

import argparse
import sys

import pygame

from i18n import STATE_LABELS
from simulation import DANGER, FOOD, HEIGHT, IDLE, MATE, MAX_POPULATION, World, WIDTH, load_seed_genome

DEFAULT_INIT_POP = 70
DEFAULT_LANGUAGE_FILE = "language_model.json"

SCALE = 5
HUD_H = 200
SCREEN_W, SCREEN_H = int(WIDTH * SCALE), int(HEIGHT * SCALE) + HUD_H

BG = (18, 22, 16)
GROUND = (30, 38, 24)
HUD_BG = (10, 12, 9)
TEXT_COLOR = (220, 220, 210)
FOOD_COLOR = (110, 220, 90)
BODY_COLOR = (222, 208, 150)
PREDATOR_COLOR = (220, 30, 30)
TOKEN_COLORS = [
    (120, 120, 120),  # 0: silence, not drawn as a ring
    (235, 70, 70),
    (70, 140, 235),
    (245, 200, 60),
    (200, 90, 230),
    (70, 225, 210),
]

TEXT = {
    "en": {
        "choose_mode_prompt": "Choose the starting mode:",
        "choose_mode_auto": "  A = automatic - food and predators spawn on their own",
        "choose_mode_manual": "  M = manual - you place everything yourself, nothing spawns alone",
        "choose_mode_hint": "Press A or M to start.",

        "choose_pop_prompt": "How many creatures to start with? (1-{max}, default {default})",
        "choose_pop_hint": "Press ENTER to confirm.",

        "choose_ai_prompt": "Activate the pre-trained AI language?",
        "choose_ai_subtitle": "  (reads '{file}', generated by train_language.py)",
        "choose_ai_yes": "  Y = yes - creatures already speak an unambiguous language",
        "choose_ai_no": "  N = no - the language has to emerge on its own while you play (default)",
        "choose_ai_hint": "Press Y or N to start.",
        "ai_missing_file": "'{file}' not found - starting without AI.",
        "flash_hint": "-- press any key to continue --",

        "hud_paused": "PAUSED",
        "hud_trained_tag": "   [trained vocabulary]",
        "hud_header": ("tick {tick:>6}   pop {pop:>4}   births {births:>5}   deaths {deaths:>5}   "
                        "{status}   (space=pause  up/down=speed  r=reset  h=help){tag}"),
        "hud_manual": "mode: manual   click places: {placing} (P)",
        "hud_auto": "mode: automatic   predators: {count} ([ / ] act immediately)",
        "placing_food": "food",
        "placing_predator": "predator",
        "hud_vocab_title": "vocabulary — every color in use per state, population share:",
        "legend_creature": "creature (ring = its current signal)",
        "legend_food": "food",
        "legend_predator": "predator",
        "extinct": "Extinct. Press R to start a new world.",

        "help_more": "-- space for more --",
        "help_dismiss": "-- press any key to resume --",
        "help_lines": [
            ("Thronglets - notice", True),
            ("", False),
            ("Each creature is born with a genome deciding which color it shows for", False),
            ("its current state, and how it reacts to colors it hears from others.", False),
            ("Nobody programs what a color means - a shared language can emerge", False),
            ("through natural selection, or it might not.", False),
            ("", False),
            ("The 4 states, in priority order:", True),
            ("  1. alarm-call  a predator was spotted -> flee immediately", False),
            ("  2. food-call   food is visible nearby", False),
            ("  3. mate-call   ready to mate, and a ready partner is nearby", False),
            ("  4. idle        nothing special (by far the most common state)", False),
            ("", False),
            ("Living, mating, dying:", True),
            ("  Energy drains constantly; eating restores it. Emitting a color", False),
            ("  (other than silence) costs a bit of extra energy. Enough energy", False),
            ("  and age, plus a matching partner nearby: a child is born. A", False),
            ("  predator that catches a creature kills it outright.", False),
            ("", False),
            ("Reading the vocabulary rows at the top:", True),
            ("  For each state, the share of the population using each color.", False),
            ("  It starts near chance (~17%) and climbs if a token wins out.", False),
            ("  A '..' swatch means silence, not a missing color.", False),
            ("", False),
            ("Worth knowing:", True),
            ("  Two states can end up sharing the same color purely by chance", False),
            ("  (e.g. idle and alarm-call) - nothing prevents it or guarantees", False),
            ("  it resolves. Signaling costs energy, so silence is a real", False),
            ("  strategy, not a default.", False),
        ],
    },
    "fr": {
        "choose_mode_prompt": "Choisis le mode de depart :",
        "choose_mode_auto": "  A = automatique - nourriture et predateurs apparaissent seuls",
        "choose_mode_manual": "  M = manuel - tu places tout toi-meme, rien ne spawn seul",
        "choose_mode_hint": "Appuie sur A ou M pour commencer.",

        "choose_pop_prompt": "Combien de creatures au depart ? (1-{max}, defaut {default})",
        "choose_pop_hint": "Appuie sur ENTREE pour confirmer.",

        "choose_ai_prompt": "Activer le langage pre-entraine par IA ?",
        "choose_ai_subtitle": "  (relit '{file}', genere par train_language.py)",
        "choose_ai_yes": "  O = oui - les creatures parlent deja un langage sans confusion",
        "choose_ai_no": "  N = non - le langage doit emerger tout seul en jouant (defaut)",
        "choose_ai_hint": "Appuie sur O ou N pour commencer.",
        "ai_missing_file": "'{file}' introuvable - lancement sans IA.",
        "flash_hint": "-- une touche pour continuer --",

        "hud_paused": "PAUSE",
        "hud_trained_tag": "   [vocabulaire entraine]",
        "hud_header": ("tick {tick:>6}   pop {pop:>4}   naissances {births:>5}   morts {deaths:>5}   "
                        "{status}   (espace=pause  haut/bas=vitesse  r=reset  h=aide){tag}"),
        "hud_manual": "mode: manuel   clic pose : {placing} (P)",
        "hud_auto": "mode: auto   predateurs : {count} ([ / ] agit tout de suite)",
        "placing_food": "nourriture",
        "placing_predator": "predateur",
        "hud_vocab_title": "vocabulaire — toutes les couleurs en usage par etat, part de la population :",
        "legend_creature": "creature (anneau = son signal actuel)",
        "legend_food": "nourriture",
        "legend_predator": "predateur",
        "extinct": "Extinction. Appuie sur R pour un nouveau monde.",

        "help_more": "-- espace pour la suite --",
        "help_dismiss": "-- une touche pour reprendre --",
        "help_lines": [
            ("Thronglets — notice", True),
            ("", False),
            ("Chaque creature nait avec un genome qui decide quelle couleur", False),
            ("elle affiche selon son etat, et comment elle reagit aux couleurs", False),
            ("des autres. Personne ne programme le sens des couleurs : un", False),
            ("langage commun peut emerger par selection naturelle, ou pas.", False),
            ("", False),
            ("Les 4 etats, par ordre de priorite :", True),
            ("  1. alerte      un predateur repere -> fuite immediate", False),
            ("  2. nourriture  de la nourriture est visible tout pres", False),
            ("  3. partenaire  prete a se reproduire + partenaire prete proche", False),
            ("  4. inactif     rien de special (etat le plus frequent, de loin)", False),
            ("", False),
            ("Vivre, se reproduire, mourir :", True),
            ("  L'energie baisse en permanence, manger la restaure. Emettre", False),
            ("  une couleur (hors silence) coute un peu d'energie en plus.", False),
            ("  Assez d'energie et d'age, un partenaire pareil a proximite :", False),
            ("  un enfant nait. Un predateur qui attrape une creature la tue.", False),
            ("", False),
            ("Lire le vocabulaire affiche en haut :", True),
            ("  Pour chaque etat, la part de la population qui utilise chaque", False),
            ("  couleur. Ca part du hasard (~17%) et grimpe si un mot fait", False),
            ("  consensus. '..' = silence, pas une couleur en moins.", False),
            ("", False),
            ("A savoir :", True),
            ("  Deux etats peuvent finir sur la meme couleur par hasard (ex:", False),
            ("  inactif et alerte) - rien ne l'empeche ni ne garantit que ca", False),
            ("  se resolve. Parler coute de l'energie : le silence est une", False),
            ("  vraie strategie, pas un defaut.", False),
        ],
    },
}


def show_help(screen, font, lang):
    t = TEXT[lang]
    lines = t["help_lines"]
    line_h = 24
    top = 20
    page_size = max(1, (SCREEN_H - top - 50) // line_h)
    for start in range(0, len(lines), page_size):
        page = lines[start:start + page_size]
        more = start + page_size < len(lines)
        footer = t["help_more"] if more else t["help_dismiss"]
        waiting = True
        while waiting:
            screen.fill(BG)
            for i, (line, bold) in enumerate(page):
                color = TEXT_COLOR if not bold else (255, 255, 255)
                screen.blit(font.render(line, True, color), (20, top + i * line_h))
            screen.blit(font.render(footer, True, (150, 155, 145)), (20, top + len(page) * line_h + 14))
            pygame.display.flip()
            for event in pygame.event.get():
                if event.type == pygame.QUIT:
                    pygame.quit()
                    sys.exit()
                elif event.type == pygame.KEYDOWN:
                    waiting = False


def draw(screen, font, world, paused, speed, mode, placing, lang, trained=False):
    screen.fill(BG)
    pygame.draw.rect(screen, GROUND, (0, HUD_H, SCREEN_W, SCREEN_H - HUD_H))

    for fx, fy in world.food:
        pygame.draw.circle(screen, FOOD_COLOR, (int(fx * SCALE), int(fy * SCALE) + HUD_H), 3)

    for c in world.creatures:
        if not c.alive:
            continue
        x, y = int(c.pos[0] * SCALE), int(c.pos[1] * SCALE) + HUD_H
        pygame.draw.circle(screen, BODY_COLOR, (x, y), 4)
        if c.token != 0:
            pygame.draw.circle(screen, TOKEN_COLORS[c.token], (x, y), 7, width=2)

    for p in world.predators:
        x, y = int(p.pos[0] * SCALE), int(p.pos[1] * SCALE) + HUD_H
        pygame.draw.circle(screen, PREDATOR_COLOR, (x, y), 6)

    draw_hud(screen, font, world, paused, speed, mode, placing, lang, trained)


def draw_vocab_row(screen, font, y, label, pairs):
    x = 10
    lbl = font.render(f"{label}:", True, TEXT_COLOR)
    screen.blit(lbl, (x, y))
    x += lbl.get_width() + 10
    for token, frac in pairs:
        if token == 0:
            pygame.draw.circle(screen, (110, 110, 110), (x + 6, y + 8), 6, width=1)
        else:
            pygame.draw.circle(screen, TOKEN_COLORS[token], (x + 6, y + 8), 6)
        txt = font.render(f"{frac * 100:3.0f}%", True, TEXT_COLOR)
        screen.blit(txt, (x + 16, y))
        x += 16 + txt.get_width() + 14


def draw_hud(screen, font, world, paused, speed, mode, placing, lang, trained=False):
    t = TEXT[lang]
    labels = STATE_LABELS[lang]
    pygame.draw.rect(screen, HUD_BG, (0, 0, SCREEN_W, HUD_H))
    pop = world.population()
    status = t["hud_paused"] if paused else f"x{speed}"
    tag = t["hud_trained_tag"] if trained else ""
    header = t["hud_header"].format(tick=world.tick, pop=pop, births=world.births,
                                     deaths=world.deaths, status=status, tag=tag)
    screen.blit(font.render(header, True, TEXT_COLOR), (10, 8))

    if mode == "manual":
        placing_label = t["placing_food"] if placing == "food" else t["placing_predator"]
        settings = t["hud_manual"].format(placing=placing_label)
    else:
        settings = t["hud_auto"].format(count=len(world.predators))
    screen.blit(font.render(settings, True, TEXT_COLOR), (10, 28))

    screen.blit(font.render(t["hud_vocab_title"], True, TEXT_COLOR), (10, 48))

    y = 70
    breakdown = world.vocabulary_breakdown()
    for state in (DANGER, FOOD, MATE, IDLE):
        draw_vocab_row(screen, font, y, labels[state], breakdown[state])
        y += 22

    legend_y = y
    lx = 10
    pygame.draw.circle(screen, BODY_COLOR, (lx + 6, legend_y + 8), 4)
    pygame.draw.circle(screen, (150, 150, 150), (lx + 6, legend_y + 8), 7, width=2)
    txt = font.render(t["legend_creature"], True, TEXT_COLOR)
    screen.blit(txt, (lx + 18, legend_y))
    lx += 18 + txt.get_width() + 20

    pygame.draw.circle(screen, FOOD_COLOR, (lx + 6, legend_y + 8), 3)
    txt = font.render(t["legend_food"], True, TEXT_COLOR)
    screen.blit(txt, (lx + 18, legend_y))
    lx += 18 + txt.get_width() + 20

    pygame.draw.circle(screen, PREDATOR_COLOR, (lx + 6, legend_y + 8), 6)
    txt = font.render(t["legend_predator"], True, TEXT_COLOR)
    screen.blit(txt, (lx + 18, legend_y))

    if pop == 0:
        msg = font.render(t["extinct"], True, (235, 90, 90))
        screen.blit(msg, (10, legend_y + 22))


def _new_world(mode, predator_count, init_pop=DEFAULT_INIT_POP, seed_genome=None):
    if mode == "manual":
        return World(init_pop=init_pop, manual_food=True, manual_predators=True, seed_genome=seed_genome)
    return World(init_pop=init_pop, predator_count=predator_count, seed_genome=seed_genome)


def choose_language(screen, font):
    lines = [
        "Thronglets",
        "",
        "Choose your language / Choisis ta langue :",
        "  E = English",
        "  F = Francais",
        "",
        "Press E or F to continue.",
    ]
    while True:
        screen.fill(BG)
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_e:
                    return "en"
                if event.key == pygame.K_f:
                    return "fr"


def choose_mode(screen, font, lang):
    t = TEXT[lang]
    lines = [
        "Thronglets",
        "",
        t["choose_mode_prompt"],
        t["choose_mode_auto"],
        t["choose_mode_manual"],
        "",
        t["choose_mode_hint"],
    ]
    while True:
        screen.fill(BG)
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_a:
                    return "auto"
                if event.key == pygame.K_m:
                    return "manual"


def choose_population(screen, font, lang):
    t = TEXT[lang]
    text = ""
    while True:
        screen.fill(BG)
        lines = [
            "Thronglets",
            "",
            t["choose_pop_prompt"].format(max=MAX_POPULATION, default=DEFAULT_INIT_POP),
            "",
            f"> {text}",
            "",
            t["choose_pop_hint"],
        ]
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_RETURN:
                    if not text:
                        return DEFAULT_INIT_POP
                    return max(1, min(MAX_POPULATION, int(text)))
                elif event.key == pygame.K_BACKSPACE:
                    text = text[:-1]
                elif event.unicode.isdigit() and len(text) < 3:
                    text += event.unicode


def choose_ai(screen, font, lang):
    t = TEXT[lang]
    lines = [
        "Thronglets",
        "",
        t["choose_ai_prompt"],
        t["choose_ai_subtitle"].format(file=DEFAULT_LANGUAGE_FILE),
        "",
        t["choose_ai_yes"],
        t["choose_ai_no"],
        "",
        t["choose_ai_hint"],
    ]
    yes_key = pygame.K_o if lang == "fr" else pygame.K_y
    while True:
        screen.fill(BG)
        for i, line in enumerate(lines):
            screen.blit(font.render(line, True, TEXT_COLOR), (20, 20 + i * 26))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                if event.key == yes_key:
                    return True
                if event.key == pygame.K_n:
                    return False


def flash_message(screen, font, lang, text):
    waiting = True
    while waiting:
        screen.fill(BG)
        screen.blit(font.render(text, True, (235, 90, 90)), (20, 20))
        screen.blit(font.render(TEXT[lang]["flash_hint"], True, TEXT_COLOR), (20, 60))
        pygame.display.flip()
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
                sys.exit()
            elif event.type == pygame.KEYDOWN:
                waiting = False


def main():
    parser = argparse.ArgumentParser(description="Thronglets - pygame renderer")
    parser.add_argument("--language", type=str, default=None,
                         help="seed the population with a train_language.py --export vocabulary "
                              "instead of starting from scratch")
    args = parser.parse_args()

    pygame.init()
    pygame.display.set_caption("Thronglets - a tiny language is being born")
    screen = pygame.display.set_mode((SCREEN_W, SCREEN_H), pygame.FULLSCREEN | pygame.SCALED)
    clock = pygame.time.Clock()
    font = pygame.font.SysFont("consolas", 16)

    lang = choose_language(screen, font)
    mode = choose_mode(screen, font, lang)
    init_pop = choose_population(screen, font, lang)

    if args.language:
        seed_genome = load_seed_genome(args.language)
    elif choose_ai(screen, font, lang):
        try:
            seed_genome = load_seed_genome(DEFAULT_LANGUAGE_FILE)
        except OSError:
            seed_genome = None
            flash_message(screen, font, lang, TEXT[lang]["ai_missing_file"].format(file=DEFAULT_LANGUAGE_FILE))
    else:
        seed_genome = None

    placing = "food"

    world = _new_world(mode, 6, init_pop, seed_genome)
    paused = False
    speed = 1
    running = True

    while running:
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False
            elif event.type == pygame.KEYDOWN:
                if event.key == pygame.K_ESCAPE:
                    running = False
                elif event.key == pygame.K_SPACE:
                    paused = not paused
                elif event.key == pygame.K_r:
                    world = _new_world(mode, len(world.predators), init_pop, seed_genome)
                elif event.key == pygame.K_UP:
                    speed = min(200, speed + (1 if speed < 10 else 10))
                elif event.key == pygame.K_DOWN:
                    speed = max(1, speed - (1 if speed <= 10 else 10))
                elif event.key == pygame.K_p:
                    placing = "predator" if placing == "food" else "food"
                elif event.key == pygame.K_LEFTBRACKET:
                    world.remove_predator()
                elif event.key == pygame.K_RIGHTBRACKET:
                    world.add_random_predator()
                elif event.key == pygame.K_h:
                    show_help(screen, font, lang)
            elif event.type == pygame.MOUSEBUTTONDOWN and event.button == 1:
                mx, my = event.pos
                if my > HUD_H:
                    wx, wy = mx / SCALE, (my - HUD_H) / SCALE
                    if mode == "manual" and placing == "predator":
                        world.add_predator(wx, wy)
                    else:
                        world.add_food(wx, wy)

        if not paused:
            for _ in range(speed):
                world.step()

        draw(screen, font, world, paused, speed, mode, placing, lang, trained=seed_genome is not None)
        pygame.display.flip()
        clock.tick(60)

    pygame.quit()
    sys.exit()


if __name__ == "__main__":
    main()
